(function(){
'use strict';var f,aa=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.10.1",fileLevelThis:this}),ba;function ca(a){for(var b in a)return b}function da(a){this.Ja=a}da.prototype.toString=function(){return String.fromCharCode(this.Ja)};
function ea(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"number"!==typeof a||a===a&&Math.fround(a)!==a?"java.lang.Double":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.$c():a instanceof g?"java.lang.Long":a instanceof da?"java.lang.Character":a&&a.$classData?a.$classData.name:
null.ad()}}function fa(a){switch(typeof a){case "string":return k(a);case "number":return ha(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a=a.u():a instanceof g?(a=null===a?ba:a,a=a.I^a.H):a=a instanceof da?null===a?0:a.Ja:n.prototype.u.call(a),a}}var ia=0,ja=new WeakMap;
function ka(a){switch(typeof a){case "string":return k(a);case "number":return ha(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:k(a);default:if(null===a)return 0;b=ja.get(a);void 0===b&&(ia=b=ia+1|0,ja.set(a,b));return b}}function n(){}n.prototype.constructor=n;function p(){}p.prototype=n.prototype;n.prototype.u=function(){return ka(this)};
n.prototype.h=function(){var a=this.u();return ea(this)+"@"+(+(a>>>0)).toString(16)};n.prototype.toString=function(){return this.h()};function q(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=null}else this.c=a}q.prototype=new p;q.prototype.constructor=q;function la(){}la.prototype=q.prototype;function ma(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=!1}else this.c=a}ma.prototype=new p;ma.prototype.constructor=ma;
function na(a){this.c="number"===typeof a?new Uint16Array(a):a}na.prototype=new p;na.prototype.constructor=na;function oa(a){this.c="number"===typeof a?new Int8Array(a):a}oa.prototype=new p;oa.prototype.constructor=oa;function pa(a){this.c="number"===typeof a?new Int16Array(a):a}pa.prototype=new p;pa.prototype.constructor=pa;function qa(a){this.c="number"===typeof a?new Int32Array(a):a}qa.prototype=new p;qa.prototype.constructor=qa;
function ra(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=ba}else this.c=a}ra.prototype=new p;ra.prototype.constructor=ra;function sa(a){this.c="number"===typeof a?new Float32Array(a):a}sa.prototype=new p;sa.prototype.constructor=sa;function ta(a){this.c="number"===typeof a?new Float64Array(a):a}ta.prototype=new p;ta.prototype.constructor=ta;
function ua(){this.q=void 0;this.K=this.p=null;this.L=0;this.mb=null;this.t="";this.B=this.J=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function r(a,b,c,d){var h=new ua;h.p={};h.mb=a;h.t=b;h.B=l=>l===h;h.name=c;h.isPrimitive=!0;h.isInstance=()=>!1;void 0!==d&&(h.J=va(h,d));return h}
function t(a,b,c,d){var h=new ua,l=ca(a);h.p=c;h.t="L"+b+";";h.B=e=>!!e.p[l];h.name=b;h.isInterface=!1;h.isInstance=d||(e=>!!(e&&e.$classData&&e.$classData.p[l]));return h}function va(a,b,c){var d=new ua;b.prototype.$classData=d;var h="["+a.t;d.q=b;d.p={a:1,fa:1,b:1};d.K=a;d.L=1;d.t=h;d.name=h;d.isArrayClass=!0;d.B=c||(l=>d===l);d.isInstance=l=>l instanceof b;return d}
function wa(a){function b(e){if("number"===typeof e){this.c=Array(e);for(var m=0;m<e;m++)this.c[m]=null}else this.c=e}var c=new ua;b.prototype=new la;b.prototype.constructor=b;var d=a.K||a,h=a.L+1;b.prototype.$classData=c;a="["+a.t;c.q=b;c.p={a:1,fa:1,b:1};c.K=d;c.L=h;c.t=a;c.name=a;c.isArrayClass=!0;var l=e=>{var m=e.L;return m===h?d.B(e.K):m>h&&d===u};c.B=l;c.isInstance=e=>{e=e&&e.$classData;return!!e&&(e===c||l(e))};return c}function v(a){a.J||(a.J=wa(a));return a.J}var u=new ua;u.p={a:1};
u.t="Ljava.lang.Object;";u.B=a=>!a.isPrimitive;u.name="java.lang.Object";u.isInstance=a=>null!==a;u.J=va(u,q,a=>{var b=a.L;return 1===b?!a.K.isPrimitive:1<b});n.prototype.$classData=u;r(void 0,"V","void",void 0);r(!1,"Z","boolean",ma);r(0,"C","char",na);r(0,"B","byte",oa);r(0,"S","short",pa);r(0,"I","int",qa);var xa=r(null,"J","long",ra);r(0,"F","float",sa);r(0,"D","double",ta);function ya(){za||(za=new Aa);var a=za;0===(33554432&a.aa)&&0===(33554432&a.aa)&&(a.rb=window,a.aa|=33554432)}
ya.prototype=new p;ya.prototype.constructor=ya;ya.prototype.$classData=t({nb:0},"dotty.tools.scaladoc.ContentContributors",{nb:1,a:1});function Ba(){this.Oa=this.ga=this.M=null;Ca=this;this.M=new ArrayBuffer(8);this.ga=new Int32Array(this.M,0,2);new Float32Array(this.M,0,2);this.Oa=new Float64Array(this.M,0,1);this.ga[0]=16909060;new Int8Array(this.M,0,8)}Ba.prototype=new p;Ba.prototype.constructor=Ba;
function Da(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.Oa[0]=b;return(a.ga[0]|0)^(a.ga[1]|0)}Ba.prototype.$classData=t({wb:0},"java.lang.FloatingPointBits$",{wb:1,a:1});var Ca;function Ea(){Ca||(Ca=new Ba);return Ca}
function Fa(){this.Pa=this.va=null;Ga=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.va=a;this.Pa=null}Fa.prototype=new p;Fa.prototype.constructor=Fa;function Ha(a,b,c){null!==a.va?(Ia||(Ia=new Ja),a=a.va,Ka||(Ka=new La),b=Ka.Ra.call(a,b)?a[b]:c):b=Ha(a.Pa,b,c);return b}Fa.prototype.$classData=t({Cb:0},"java.lang.System$SystemProperties$",{Cb:1,a:1});var Ga;function Ja(){}Ja.prototype=new p;Ja.prototype.constructor=Ja;Ja.prototype.$classData=t({Hb:0},"java.lang.Utils$",{Hb:1,a:1});var Ia;function La(){this.Ra=null;Ka=this;this.Ra=Object.prototype.hasOwnProperty}
La.prototype=new p;La.prototype.constructor=La;La.prototype.$classData=t({Ib:0},"java.lang.Utils$Cache$",{Ib:1,a:1});var Ka;function Ma(){}Ma.prototype=new p;Ma.prototype.constructor=Ma;Ma.prototype.$classData=t({Jb:0},"java.util.Arrays$",{Jb:1,a:1});var Na;function Aa(){this.rb=null;this.aa=0}Aa.prototype=new p;Aa.prototype.constructor=Aa;Aa.prototype.$classData=t({qb:0},"org.scalajs.dom.package$",{qb:1,a:1});var za;function g(a,b){this.I=a;this.H=b}g.prototype=new p;g.prototype.constructor=g;
g.prototype.u=function(){return this.I^this.H};g.prototype.h=function(){Oa();var a=this.I,b=this.H;return b===a>>31?""+a:0>b?"-"+Pa(-a|0,0!==a?~b:-b|0):Pa(a,b)};g.prototype.$classData=t({sb:0},"org.scalajs.linker.runtime.RuntimeLong",{sb:1,a:1});
function Pa(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+Math.clz32(1E9)|0)-(0!==b?Math.clz32(b):32+Math.clz32(a)|0)|0,d=c,h=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var l=a,e=b;for(a=b=0;0<=c&&0!==(-2097152&e);){var m=l,A=e,z=h,Q=d;if(A===Q?(-2147483648^m)>=(-2147483648^z):(-2147483648^A)>=(-2147483648^Q))m=e,A=d,e=l-h|0,m=(-2147483648^e)>(-2147483648^l)?-1+(m-A|0)|0:m-A|0,l=e,e=m,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;m=d>>>1|0;h=h>>>1|0|d<<31;d=m}c=e;if(0===
c?-1147483648<=(-2147483648^l):-2147483648<=(-2147483648^c))c=4294967296*e+ +(l>>>0),l=c/1E9,h=l/4294967296|0,d=b,b=l=d+(l|0)|0,a=(-2147483648^l)<(-2147483648^d)?1+(a+h|0)|0:a+h|0,l=c%1E9|0;c=""+l;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function Qa(){this.ba=0}Qa.prototype=new p;Qa.prototype.constructor=Qa;
function Ra(a,b){if(-0x7fffffffffffffff>b)return a.ba=-2147483648,0;if(0x7fffffffffffffff<=b)return a.ba=2147483647,-1;var c=b|0,d=b/4294967296|0;a.ba=0>b&&0!==c?-1+d|0:d;return c}Qa.prototype.$classData=t({tb:0},"org.scalajs.linker.runtime.RuntimeLong$",{tb:1,a:1});var Sa;function Oa(){Sa||(Sa=new Qa);return Sa}
function Ta(a,b,c,d,h){var l=b.o;0!==(c.length|0)&&(l.e=""+l.e+c);a=a.k();if(a.i())for(c=a.g(),l.e=""+l.e+c;a.i();)l.e=""+l.e+d,c=a.g(),l.e=""+l.e+c;0!==(h.length|0)&&(l.e=""+l.e+h);return b}function Ua(){this.ib=null;Va=this;this.ib=new q(0);new (v(v(u)).q)(0);new (v(v(v(u))).q)(0);new (v(v(v(v(u)))).q)(0);new (v(v(v(v(v(u))))).q)(0);new (v(v(v(v(v(v(u)))))).q)(0)}Ua.prototype=new p;Ua.prototype.constructor=Ua;Ua.prototype.$classData=t({Dc:0},"scala.collection.immutable.VectorStatics$",{Dc:1,a:1});
var Va;function Wa(){Va||(Va=new Ua);return Va}function Xa(){}Xa.prototype=new p;Xa.prototype.constructor=Xa;Xa.prototype.$classData=t({Mc:0},"scala.collection.mutable.MutationTracker$",{Mc:1,a:1});var Ya;function Za(){}Za.prototype=new p;Za.prototype.constructor=Za;Za.prototype.$classData=t({ic:0},"scala.collection.package$$colon$plus$",{ic:1,a:1});var $a;function ab(){}ab.prototype=new p;ab.prototype.constructor=ab;ab.prototype.$classData=t({jc:0},"scala.collection.package$$plus$colon$",{jc:1,a:1});
var bb;function cb(){}cb.prototype=new p;cb.prototype.constructor=cb;cb.prototype.$classData=t({Rb:0},"scala.math.Ordered$",{Rb:1,a:1});var db;
function eb(){this.Ta=null;fb=this;gb||(gb=new w);gb||(gb=new w);hb||(hb=new ib);jb||(jb=new kb);x();lb();this.Ta=y();mb||(mb=new B);bb||(bb=new ab);$a||($a=new Za);nb||(nb=new ob);pb();qb();rb||(rb=new sb);tb||(tb=new ub);vb||(vb=new wb);xb||(xb=new yb);Bb||(Bb=new Cb);Db||(Db=new Eb);db||(db=new cb);Fb||(Fb=new Gb);Hb||(Hb=new Ib);Jb||(Jb=new C);Kb||(Kb=new D)}eb.prototype=new p;eb.prototype.constructor=eb;eb.prototype.$classData=t({Tb:0},"scala.package$",{Tb:1,a:1});var fb;function Lb(){}
Lb.prototype=new p;Lb.prototype.constructor=Lb;function E(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{var c=Oa();b=Ra(c,a);c=c.ba;Oa();a=(0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0))===a?b^c:Da(Ea(),a)}return a}return b instanceof g?(a=null===b?ba:b,b=new g(a.I,a.H),a=b.I,b=b.H,b===a>>31?a:a^b):fa(b)}Lb.prototype.$classData=t({Yc:0},"scala.runtime.Statics$",{Yc:1,a:1});var Mb;
function F(){Mb||(Mb=new Lb);return Mb}function Nb(){}Nb.prototype=new p;Nb.prototype.constructor=Nb;Nb.prototype.$classData=t({Vc:0},"scala.scalajs.runtime.package$",{Vc:1,a:1});var Ob;function Pb(){}Pb.prototype=new p;Pb.prototype.constructor=Pb;function Qb(){}Qb.prototype=Pb.prototype;function G(a,b){a=Rb(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function Rb(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}
function H(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function Sb(a){0===(32&a.ea)<<24>>24&&0===(32&a.ea)<<24>>24&&(a.Na=new qa(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.ea=(32|a.ea)<<24>>24);return a.Na}
function Tb(){this.Na=null;this.ea=0}Tb.prototype=new p;Tb.prototype.constructor=Tb;Tb.prototype.$classData=t({vb:0},"java.lang.Character$",{vb:1,a:1,b:1});var Ub;function Vb(a){throw new Wb('For input string: "'+a+'"');}function Xb(){}Xb.prototype=new p;Xb.prototype.constructor=Xb;Xb.prototype.$classData=t({yb:0},"java.lang.Integer$",{yb:1,a:1,b:1});var Yb;
function I(a,b){a.Qa=b;a.Db=null;a.Eb=!0;a.Fb=!0;"[object Error]"!==Object.prototype.toString.call(a)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(a)}class Zb extends Error{constructor(){super();this.Db=this.Qa=null;this.Fb=this.Eb=!1}ua(){return this.Qa}h(){var a=ea(this),b=this.ua();return null===b?a:a+": "+b}u(){return n.prototype.u.call(this)}get message(){var a=this.ua();return null===a?"":a}get name(){return ea(this)}toString(){return this.h()}}function B(){}B.prototype=new p;
B.prototype.constructor=B;B.prototype.h=function(){return"::"};B.prototype.$classData=t({kc:0},"scala.collection.immutable.$colon$colon$",{kc:1,a:1,b:1});var mb;function ub(){}ub.prototype=new p;ub.prototype.constructor=ub;ub.prototype.$classData=t({xc:0},"scala.collection.immutable.Range$",{xc:1,a:1,b:1});var tb;function sb(){}sb.prototype=new p;sb.prototype.constructor=sb;sb.prototype.$classData=t({Tc:0},"scala.collection.mutable.StringBuilder$",{Tc:1,a:1,b:1});var rb;function yb(){}
yb.prototype=new p;yb.prototype.constructor=yb;yb.prototype.$classData=t({Ob:0},"scala.math.Fractional$",{Ob:1,a:1,b:1});var xb;function Cb(){}Cb.prototype=new p;Cb.prototype.constructor=Cb;Cb.prototype.$classData=t({Pb:0},"scala.math.Integral$",{Pb:1,a:1,b:1});var Bb;function Eb(){}Eb.prototype=new p;Eb.prototype.constructor=Eb;Eb.prototype.$classData=t({Qb:0},"scala.math.Numeric$",{Qb:1,a:1,b:1});var Db;function $b(){}$b.prototype=new p;$b.prototype.constructor=$b;function ac(){}ac.prototype=$b.prototype;
$b.prototype.h=function(){return"\x3cfunction0\x3e"};function J(a){this.Ga=a}J.prototype=new p;J.prototype.constructor=J;J.prototype.h=function(){return""+this.Ga};J.prototype.$classData=t({Wc:0},"scala.runtime.IntRef",{Wc:1,a:1,b:1});function K(a){this.Ha=a}K.prototype=new p;K.prototype.constructor=K;K.prototype.h=function(){return""+this.Ha};K.prototype.$classData=t({Xc:0},"scala.runtime.ObjectRef",{Xc:1,a:1,b:1});function Ib(){}Ib.prototype=new p;Ib.prototype.constructor=Ib;
Ib.prototype.$classData=t({Ub:0},"scala.util.Either$",{Ub:1,a:1,b:1});var Hb;function C(){}C.prototype=new p;C.prototype.constructor=C;C.prototype.h=function(){return"Left"};C.prototype.$classData=t({Vb:0},"scala.util.Left$",{Vb:1,a:1,b:1});var Jb;function D(){}D.prototype=new p;D.prototype.constructor=D;D.prototype.h=function(){return"Right"};D.prototype.$classData=t({Wb:0},"scala.util.Right$",{Wb:1,a:1,b:1});var Kb;
function bc(){this.Ua=this.ka=0;cc=this;this.ka=k("Seq");this.Ua=k("Map");k("Set");fb||(fb=new eb);for(var a=this.Ua,b=0,c=0,d=0,h=1,l=fb.Ta.k();l.i();){var e=l.g();e=E(F(),e);b=b+e|0;c^=e;h=Math.imul(h,1|e);d=1+d|0}a=G(a,b);a=G(a,c);a=Rb(a,h);H(a^d)}bc.prototype=new Qb;bc.prototype.constructor=bc;bc.prototype.$classData=t({Xb:0},"scala.util.hashing.MurmurHash3$",{Xb:1,ld:1,a:1});var cc;function dc(){this.Ia=this.pb=null;ec=this;var a=Oa(),b=+(new Date).getTime();Ra(a,b);this.Ia=new fc;new ya}
dc.prototype=new p;dc.prototype.constructor=dc;dc.prototype.$classData=t({ob:0},"dotty.tools.scaladoc.Main$",{ob:1,a:1,hd:1,gd:1});var ec;class gc extends Zb{}function hc(){}hc.prototype=new p;hc.prototype.constructor=hc;function ic(){}ic.prototype=hc.prototype;function jc(a,b){if(0>b)return 1;var c=a.C();if(0<=c)return c===b?0:c<b?-1:1;c=0;for(a=a.k();a.i();){if(c===b)return 1;a.g();c=1+c|0}return c-b|0}function kc(){this.x=null;lc=this;this.x=new L}kc.prototype=new p;kc.prototype.constructor=kc;
kc.prototype.$classData=t({cc:0},"scala.collection.Iterator$",{cc:1,a:1,s:1,b:1});var lc;function x(){lc||(lc=new kc);return lc}function M(){}M.prototype=new p;M.prototype.constructor=M;M.prototype.A=function(){throw new mc("head of empty lazy list");};function N(){throw new nc("tail of empty lazy list");}M.prototype.$classData=t({qc:0},"scala.collection.immutable.LazyList$State$Empty$",{qc:1,a:1,wd:1,b:1});var oc;function pc(){oc||(oc=new M);return oc}function wb(){}wb.prototype=new p;
wb.prototype.constructor=wb;wb.prototype.$classData=t({Nb:0},"scala.math.Equiv$",{Nb:1,a:1,jd:1,b:1});var vb;function Gb(){}Gb.prototype=new p;Gb.prototype.constructor=Gb;Gb.prototype.$classData=t({Sb:0},"scala.math.Ordering$",{Sb:1,a:1,kd:1,b:1});var Fb;function O(a){this.sa=a}O.prototype=new ac;O.prototype.constructor=O;O.prototype.$classData=t({Uc:0},"scala.scalajs.runtime.AnonFunction0",{Uc:1,Fd:1,a:1,Zc:1});class P extends gc{}
P.prototype.$classData=t({r:0},"java.lang.RuntimeException",{r:1,v:1,w:1,a:1,b:1});function qc(a){a.e="";return a}function R(){this.e=null}R.prototype=new p;R.prototype.constructor=R;R.prototype.h=function(){return this.e};R.prototype.f=function(){return this.e.length|0};R.prototype.$classData=t({Bb:0},"java.lang.StringBuilder",{Bb:1,a:1,Ma:1,bd:1,b:1});function S(){}S.prototype=new p;S.prototype.constructor=S;function rc(){}rc.prototype=S.prototype;S.prototype.k=function(){return this};
S.prototype.d=function(){return!this.i()};S.prototype.h=function(){return"\x3citerator\x3e"};S.prototype.ca=function(a,b,c,d){return Ta(this,a,b,c,d)};function w(){sc||(sc=new tc)}w.prototype=new ic;w.prototype.constructor=w;w.prototype.$classData=t({ac:0},"scala.collection.Iterable$",{ac:1,bc:1,a:1,s:1,b:1});var gb;function uc(){}uc.prototype=new p;uc.prototype.constructor=uc;function vc(){}vc.prototype=uc.prototype;function tc(){lb()}tc.prototype=new ic;tc.prototype.constructor=tc;
tc.prototype.$classData=t({mc:0},"scala.collection.immutable.Iterable$",{mc:1,bc:1,a:1,s:1,b:1});var sc;function wc(){this.bb=null;xc=this;this.bb=yc(new T(new O(()=>pc())))}wc.prototype=new p;wc.prototype.constructor=wc;function zc(a,b,c){var d=new K(b),h=new J(c);return new T(new O(()=>{for(var l=d.Ha,e=h.Ga;0<e&&!l.d();)l=N(U(l)),d.Ha=l,e=-1+e|0,h.Ga=e;return U(l)}))}wc.prototype.$classData=t({oc:0},"scala.collection.immutable.LazyList$",{oc:1,a:1,S:1,s:1,b:1});var xc;
function pb(){xc||(xc=new wc);return xc}function ob(){}ob.prototype=new p;ob.prototype.constructor=ob;ob.prototype.$classData=t({zc:0},"scala.collection.immutable.Stream$",{zc:1,a:1,S:1,s:1,b:1});var nb;class Ac extends P{}class Bc extends P{constructor(a){super();I(this,a)}}Bc.prototype.$classData=t({xb:0},"java.lang.IndexOutOfBoundsException",{xb:1,r:1,v:1,w:1,a:1,b:1});t({zb:0},"java.lang.NullPointerException",{zb:1,r:1,v:1,w:1,a:1,b:1});class nc extends P{constructor(a){super();I(this,a)}}
nc.prototype.$classData=t({Gb:0},"java.lang.UnsupportedOperationException",{Gb:1,r:1,v:1,w:1,a:1,b:1});class Cc extends P{constructor(){super();I(this,"mutation occurred during iteration")}}Cc.prototype.$classData=t({Kb:0},"java.util.ConcurrentModificationException",{Kb:1,r:1,v:1,w:1,a:1,b:1});class mc extends P{constructor(a){super();I(this,a)}}mc.prototype.$classData=t({Lb:0},"java.util.NoSuchElementException",{Lb:1,r:1,v:1,w:1,a:1,b:1});
class Dc extends P{constructor(a){super();this.Sa=null;this.wa=!1;this.ia=a;I(this,null)}ua(){if(!this.wa&&!this.wa){if(null===this.ia)var a="null";else try{var b=this.ia;a=(void 0===b?"undefined":b.toString())+" (of class "+ea(this.ia)+")"}catch(c){a="an instance of class "+ea(this.ia)}this.Sa=a;this.wa=!0}return this.Sa}}Dc.prototype.$classData=t({Mb:0},"scala.MatchError",{Mb:1,r:1,v:1,w:1,a:1,b:1});function L(){}L.prototype=new rc;L.prototype.constructor=L;L.prototype.i=function(){return!1};
L.prototype.g=function(){throw new mc("next on empty iterator");};L.prototype.$classData=t({dc:0},"scala.collection.Iterator$$anon$19",{dc:1,xa:1,a:1,ma:1,l:1,m:1});function Ec(a,b){if(0>b)throw new Bc(""+b);a=a.Ka(b);if(a.d())throw new Bc(""+b);return a.La()}function kb(){qb()}kb.prototype=new vc;kb.prototype.constructor=kb;kb.prototype.$classData=t({lc:0},"scala.collection.immutable.IndexedSeq$",{lc:1,gc:1,a:1,S:1,s:1,b:1});var jb;function V(a){this.Aa=a}V.prototype=new rc;
V.prototype.constructor=V;V.prototype.i=function(){return!this.Aa.d()};V.prototype.g=function(){if(this.Aa.d())return x().x.g();U(this.Aa).A()};V.prototype.$classData=t({pc:0},"scala.collection.immutable.LazyList$LazyIterator",{pc:1,xa:1,a:1,ma:1,l:1,m:1});function Fc(){Gc=this;y();y()}Fc.prototype=new p;Fc.prototype.constructor=Fc;Fc.prototype.$classData=t({tc:0},"scala.collection.immutable.List$",{tc:1,a:1,hc:1,S:1,s:1,b:1});var Gc;function lb(){Gc||(Gc=new Fc)}
function Hc(a,b,c){this.eb=this.pa=this.X=this.W=this.V=null;this.qa=b;this.vc=c;this.E=a.G;this.Da=this.E.c.length;this.Ea=this.n=0;this.y=this.qa;this.Z=0;this.F=1;this.Fa=0;this.Y=this.Da}Hc.prototype=new p;Hc.prototype.constructor=Hc;f=Hc.prototype;f.k=function(){return this};f.d=function(){return this.y<=this.n};f.h=function(){return"\x3citerator\x3e"};f.ca=function(a,b,c,d){return Ta(this,a,b,c,d)};f.i=function(){return this.y>this.n};
f.g=function(){if(this.n===this.Da){var a=(this.n-this.y|0)+this.qa|0;if(a===this.Y){this.y<=this.n&&x().x.g();this.Z=1+this.Z|0;for(var b=null;0===b.c.length;)this.Z=1+this.Z|0,b=null;this.Fa=this.Y;var c=this.vc/2|0,d=this.Z-c|0;c=this.F=(1+c|0)-(0>d?-d|0:d)|0;switch(c){case 1:this.E=b;break;case 2:this.V=b;break;case 3:this.W=b;break;case 4:this.X=b;break;case 5:this.pa=b;break;case 6:this.eb=b;break;default:throw new Dc(c);}this.Y=this.Fa+Math.imul(b.c.length,1<<Math.imul(5,-1+this.F|0))|0;this.Y>
this.qa&&(this.Y=this.qa);1<this.F&&(this.Ea=-1+(1<<Math.imul(5,this.F))|0)}1<this.F&&(a=a-this.Fa|0,b=this.Ea^a,1024>b?this.E=this.V.c[31&(a>>>5|0)]:(32768>b?this.V=this.W.c[31&(a>>>10|0)]:(1048576>b?this.W=this.X.c[31&(a>>>15|0)]:(33554432>b?this.X=this.pa.c[31&(a>>>20|0)]:(this.pa=this.eb.c[a>>>25|0],this.X=this.pa.c[0]),this.W=this.X.c[0]),this.V=this.W.c[0]),this.E=this.V.c[0]),this.Ea=a);this.y=this.y-this.n|0;a=this.E.c.length;b=this.y;this.Da=a<b?a:b;this.n=0}a=this.E.c[this.n];this.n=1+this.n|
0;return a};f.$classData=t({uc:0},"scala.collection.immutable.NewVectorIterator",{uc:1,a:1,ma:1,l:1,m:1,fa:1});function ib(){lb()}ib.prototype=new vc;ib.prototype.constructor=ib;ib.prototype.$classData=t({yc:0},"scala.collection.immutable.Seq$",{yc:1,gc:1,a:1,S:1,s:1,b:1});var hb;
function Ic(){this.hb=null;Jc=this;try{var a=Ha;Ga||(Ga=new Fa);var b=a(Ga,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");Yb||(Yb=new Xb);var c=null===b?0:b.length|0;0===c&&Vb(b);var d=65535&(b.charCodeAt(0)|0),h=45===d;a=h?2147483648:2147483647;d=h||43===d?1:0;d>=(b.length|0)&&Vb(b);for(h=0;d!==c;){Ub||(Ub=new Tb);var l=Ub,e=65535&(b.charCodeAt(d)|0);if(256>e)var m=48<=e&&57>=e?-48+e|0:65<=e&&90>=e?-55+e|0:97<=e&&122>=e?-87+e|0:-1;else if(65313<=e&&65338>=e)m=-65303+e|
0;else if(65345<=e&&65370>=e)m=-65335+e|0;else{var A=Sb(l);Na||(Na=new Ma);b:for(var z=0,Q=A.c.length;;){if(z===Q){var zb=-1-z|0;break b}var Ab=(z+Q|0)>>>1|0,Vc=A.c[Ab],Wc=e===Vc?0:e<Vc?-1:1;if(0>Wc)Q=Ab;else{if(0===Wc){zb=Ab;break b}z=1+Ab|0}}z=0>zb?-2-zb|0:zb;if(0>z)m=-1;else{var Xc=e-Sb(l).c[z]|0;m=9<Xc?-1:Xc}}var Yc=10>m?m:-1;h=10*h+Yc;(-1===Yc||h>a)&&Vb(b);d=1+d|0}}catch(ud){throw ud;}this.hb=new Hc(Kc(),0,0)}Ic.prototype=new p;Ic.prototype.constructor=Ic;
Ic.prototype.$classData=t({Bc:0},"scala.collection.immutable.Vector$",{Bc:1,a:1,hc:1,S:1,s:1,b:1});var Jc;function qb(){Jc||(Jc=new Ic);return Jc}function W(a,b){this.kb=0;this.lb=a;this.Oc=b;this.kb=(0,b.sa)()|0}W.prototype=new rc;W.prototype.constructor=W;W.prototype.i=function(){Ya||(Ya=new Xa);var a=this.kb;if(((0,this.Oc.sa)()|0)!==a)throw new Cc;return this.lb.i()};W.prototype.g=function(){return this.lb.g()};
W.prototype.$classData=t({Nc:0},"scala.collection.mutable.MutationTracker$CheckedIterator",{Nc:1,xa:1,a:1,ma:1,l:1,m:1});function ha(a){a=+a;return Da(Ea(),a)}class Wb extends Ac{constructor(a){super();I(this,a)}}Wb.prototype.$classData=t({Ab:0},"java.lang.NumberFormatException",{Ab:1,dd:1,r:1,v:1,w:1,a:1,b:1});function k(a){for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+Math.imul(65535&(a.charCodeAt(d)|0),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}
var Lc=t({ub:0},"java.lang.String",{ub:1,a:1,b:1,cd:1,Ma:1,ed:1,fd:1},a=>"string"===typeof a);function Mc(){}Mc.prototype=new p;Mc.prototype.constructor=Mc;function Nc(){}Nc.prototype=Mc.prototype;Mc.prototype.da=function(){return this.z()};Mc.prototype.ca=function(a,b,c,d){return Ta(this,a,b,c,d)};function X(a){this.O=0;this.$b=a;this.ya=0;this.O=a.f()}X.prototype=new rc;X.prototype.constructor=X;X.prototype.i=function(){return 0<this.O};
X.prototype.g=function(){if(0<this.O){var a=this.$b.j(this.ya);this.ya=1+this.ya|0;this.O=-1+this.O|0;return a}return x().x.g()};X.prototype.$classData=t({Zb:0},"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{Zb:1,xa:1,a:1,ma:1,l:1,m:1,b:1});function Oc(){}Oc.prototype=new Nc;Oc.prototype.constructor=Oc;function Pc(){}Pc.prototype=Oc.prototype;Oc.prototype.h=function(){return this.z()+"(\x3cnot computed\x3e)"};function Y(){}Y.prototype=new Nc;Y.prototype.constructor=Y;function Qc(){}
Qc.prototype=Y.prototype;
Y.prototype.u=function(){cc||(cc=new bc);var a=cc;if(this&&this.$classData&&this.$classData.p.Va)a:{var b=a.ka;a=this.f();switch(a){case 0:a=H(b^0);break a;case 1:a=b;b=this.j(0);a=H(G(a,E(F(),b))^1);break a;default:var c=this.j(0),d=E(F(),c);c=b=G(b,d);var h=this.j(1);h=E(F(),h);var l=h-d|0;for(d=2;d<a;){b=G(b,h);var e=this.j(d);e=E(F(),e);if(l!==(e-h|0)){b=G(b,e);for(d=1+d|0;d<a;)c=this.j(d),b=G(b,E(F(),c)),d=1+d|0;a=H(b^a);break a}h=e;d=1+d|0}a=H(G(G(c,l),h))}}else if(this instanceof Rc){for(a=
a.ka;!this.d();)this.A();a=H(a^0)}else a:if(b=a.ka,a=this.k(),a.i())if(c=a.g(),a.i()){d=a.g();l=E(F(),c);c=b=G(b,l);h=E(F(),d);l=h-l|0;for(d=2;a.i();){b=G(b,h);e=a.g();e=E(F(),e);if(l!==(e-h|0)){b=G(b,e);for(d=1+d|0;a.i();)c=a.g(),b=G(b,E(F(),c)),d=1+d|0;a=H(b^d);break a}h=e;d=1+d|0}a=H(G(G(c,l),h))}else a=H(G(b,E(F(),c))^1);else a=H(b^0);return a};Y.prototype.h=function(){var a=this.da()+"(";if(this.d())a=""+a+")";else{var b=this.ca,c=new Sc;c.o=qc(new R);a=b.call(this,c,a,", ",")").o.e}return a};
Y.prototype.D=function(a){return jc(this,a)};Y.prototype.d=function(){return 0===this.D(0)};function Tc(){}Tc.prototype=new Pc;Tc.prototype.constructor=Tc;function Uc(){}Uc.prototype=Tc.prototype;function Z(){this.oa=null}Z.prototype=new Uc;Z.prototype.constructor=Z;function Zc(){}Zc.prototype=Z.prototype;Z.prototype.j=function(a){return this.oa.j(a)};Z.prototype.f=function(){return this.oa.f()};Z.prototype.d=function(){return this.oa.d()};function $c(a){this.oa=a}$c.prototype=new Zc;
$c.prototype.constructor=$c;f=$c.prototype;f.k=function(){return new X(this)};f.z=function(){return"IndexedSeqView"};f.D=function(a){var b=this.f();return b===a?0:b<a?-1:1};f.C=function(){return this.f()};f.$classData=t({Yb:0},"scala.collection.IndexedSeqView$Id",{Yb:1,qd:1,md:1,nd:1,N:1,a:1,P:1,l:1,R:1,m:1,Q:1,sd:1,b:1,pd:1,T:1,od:1,Wa:1});function ad(){}ad.prototype=new Qc;ad.prototype.constructor=ad;function bd(){}bd.prototype=ad.prototype;function cd(){}cd.prototype=new Qc;
cd.prototype.constructor=cd;function dd(){}dd.prototype=cd.prototype;function ed(a,b,c,d){b.e=""+b.e+c;a.U?a.d()||U(a).A():b.e+="\x3cnot computed\x3e";b.e=""+b.e+d;return b}function T(a){this.db=null;this.Ba=!1;this.cb=a;this.Ca=this.U=!1}T.prototype=new bd;T.prototype.constructor=T;f=T.prototype;f.z=function(){return"LinearSeq"};f.f=function(){for(var a=this,b=0;!a.d();)b=1+b|0,a=a.ta();return b};
f.D=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.d()?0:1;break a}if(b.d()){a=-1;break a}c=1+c|0;b=b.ta()}return a};f.j=function(a){return Ec(this,a)};function U(a){if(!a.Ba&&!a.Ba){if(a.Ca)throw Ob||(Ob=new Nb),a=new P,I(a,"self-referential LazyList or a derivation thereof has no more elements"),a;a.Ca=!0;try{var b=(0,a.cb.sa)()}finally{a.Ca=!1}a.U=!0;a.cb=null;a.db=b;a.Ba=!0}return a.db}f.d=function(){return U(this)===pc()};f.C=function(){return this.U&&this.d()?0:-1};f.La=function(){U(this).A()};
function yc(a){var b=a,c=a;for(b.d()||(b=N(U(b)));c!==b&&!b.d();){b=N(U(b));if(b.d())break;b=N(U(b));if(b===c)break;c=N(U(c))}return a}f.k=function(){return this.U&&this.d()?x().x:new V(this)};f.da=function(){return"LazyList"};f.ca=function(a,b,c,d){yc(this);ed(this,a.o,b,d);return a};f.h=function(){var a=new R;qc(a);a.e="LazyList";return ed(this,a,"(",")").e};f.Ka=function(a){return 0>=a?this:this.U&&this.d()?pb().bb:zc(pb(),this,a)};f.ta=function(){return N(U(this))};
f.$classData=t({nc:0},"scala.collection.immutable.LazyList",{nc:1,$a:1,la:1,N:1,a:1,P:1,l:1,R:1,m:1,Q:1,na:1,ja:1,$:1,T:1,ha:1,fb:1,ab:1,gb:1,rc:1,ec:1,fc:1,sc:1,b:1});function fd(){}fd.prototype=new dd;fd.prototype.constructor=fd;function gd(){}gd.prototype=fd.prototype;function hd(){this.G=null}hd.prototype=new bd;hd.prototype.constructor=hd;function id(){}f=id.prototype=hd.prototype;f.z=function(){return"IndexedSeq"};f.D=function(a){var b=this.f();return b===a?0:b<a?-1:1};f.C=function(){return this.f()};
f.f=function(){return this instanceof jd?this.za:this.G.c.length};f.k=function(){return Kc()===this?qb().hb:new Hc(this,this.f(),0)};f.da=function(){return"Vector"};function Rc(){}Rc.prototype=new bd;Rc.prototype.constructor=Rc;function kd(){}f=kd.prototype=Rc.prototype;f.z=function(){return"LinearSeq"};f.j=function(a){return Ec(this,a)};f.d=function(){return this===y()};f.f=function(){for(var a=0;!this.d();)a=1+a|0,ld();return a};
f.D=function(a){if(0>a)a=1;else a:for(;;){if(0===a){a=this.d()?0:1;break a}if(this.d()){a=-1;break a}ld()}return a};f.da=function(){return"List"};f.Ka=function(a){a:for(var b=this;;){if(0>=a||b.d())break a;a=-1+a|0;b=b.ta()}return b};function md(){this.G=null}md.prototype=new id;md.prototype.constructor=md;function nd(){}nd.prototype=md.prototype;function jd(){this.G=null;this.za=0}jd.prototype=new nd;jd.prototype.constructor=jd;function od(){}od.prototype=jd.prototype;
function pd(){qd=this;y();y()}pd.prototype=new kd;pd.prototype.constructor=pd;f=pd.prototype;f.A=function(){throw new mc("head of empty list");};function ld(){throw new nc("tail of empty list");}f.C=function(){return 0};f.k=function(){return x().x};f.ta=function(){ld()};f.La=function(){this.A()};f.$classData=t({wc:0},"scala.collection.immutable.Nil$",{wc:1,xd:1,$a:1,la:1,N:1,a:1,P:1,l:1,R:1,m:1,Q:1,na:1,ja:1,$:1,T:1,ha:1,fb:1,ab:1,gb:1,rc:1,ec:1,fc:1,sc:1,rd:1,Ya:1,Xa:1,Ac:1,Za:1,b:1,id:1});var qd;
function y(){qd||(qd=new pd);return qd}function rd(){this.G=null;this.za=0;var a=Wa().ib;Wa();this.za=0;this.G=a}rd.prototype=new od;rd.prototype.constructor=rd;rd.prototype.j=function(a){throw new Bc(a+" is out of bounds (empty vector)");};rd.prototype.$classData=t({Cc:0},"scala.collection.immutable.Vector0$",{Cc:1,td:1,zd:1,yd:1,$a:1,la:1,N:1,a:1,P:1,l:1,R:1,m:1,Q:1,na:1,ja:1,$:1,T:1,ha:1,fb:1,ab:1,gb:1,ud:1,Va:1,Wa:1,vd:1,Ac:1,Ya:1,Xa:1,Za:1,b:1});var sd;
function Kc(){sd||(sd=new rd);return sd}function Sc(){this.o=null}Sc.prototype=new dd;Sc.prototype.constructor=Sc;f=Sc.prototype;f.z=function(){return"IndexedSeq"};f.k=function(){var a=new $c(this);return new X(a)};f.D=function(a){var b=this.o.f();return b===a?0:b<a?-1:1};f.f=function(){return this.o.f()};f.C=function(){return this.o.f()};f.h=function(){return this.o.e};f.d=function(){return 0===this.o.f()};f.j=function(a){return new da(65535&(this.o.e.charCodeAt(a)|0))};
f.$classData=t({Sc:0},"scala.collection.mutable.StringBuilder",{Sc:1,Ec:1,la:1,N:1,a:1,P:1,l:1,R:1,m:1,Q:1,na:1,ja:1,$:1,T:1,ha:1,Qc:1,Jc:1,Rc:1,Hc:1,fa:1,Pc:1,Fc:1,Ic:1,Gc:1,Cd:1,Va:1,Wa:1,Dd:1,Ma:1,b:1});function fc(){this.jb=null;this.Lc=this.ra=0;this.jb=y();this.ra=0}fc.prototype=new gd;fc.prototype.constructor=fc;f=fc.prototype;f.k=function(){return new W(x().x,new O(()=>this.Lc))};f.j=function(a){return Ec(this.jb,a)};f.f=function(){return this.ra};f.C=function(){return this.ra};
f.d=function(){return 0===this.ra};f.z=function(){return"ListBuffer"};f.$classData=t({Kc:0},"scala.collection.mutable.ListBuffer",{Kc:1,Ad:1,Ec:1,la:1,N:1,a:1,P:1,l:1,R:1,m:1,Q:1,na:1,ja:1,$:1,T:1,ha:1,Qc:1,Jc:1,Rc:1,Hc:1,fa:1,Bd:1,Ic:1,Gc:1,Ed:1,Ya:1,Xa:1,Pc:1,Fc:1,Za:1,b:1});ba=new g(0,0);xa.mb=ba;var td=new (v(Lc).q)([]),vd;ec||(ec=new dc);vd=ec;vd.pb=td;for(var wd=vd.Ia.k();wd.i();)(0,wd.g().sa)();
}).call(this);
//# sourceMappingURL=scaladoc-js-contributors-opt.js.map
