pages = [{"l":"index.html#","e":false,"n":"Scala 3 Reference","t":"Scala 3 Reference","d":"","k":"static"},
{"l":"new-types/index.html#","e":false,"n":"New Types","t":"New Types","d":"","k":"static"},
{"l":"new-types/intersection-types.html#","e":false,"n":"Intersection Types","t":"Intersection Types","d":"","k":"static"},
{"l":"new-types/intersection-types-spec.html#","e":false,"n":"Intersection Types - More Details","t":"Intersection Types - More Details","d":"","k":"static"},
{"l":"new-types/union-types.html#","e":false,"n":"Union Types","t":"Union Types","d":"","k":"static"},
{"l":"new-types/union-types-spec.html#","e":false,"n":"Union Types - More Details","t":"Union Types - More Details","d":"","k":"static"},
{"l":"new-types/type-lambdas.html#","e":false,"n":"Type Lambdas","t":"Type Lambdas","d":"","k":"static"},
{"l":"new-types/type-lambdas-spec.html#","e":false,"n":"Type Lambdas - More Details","t":"Type Lambdas - More Details","d":"","k":"static"},
{"l":"new-types/match-types.html#","e":false,"n":"Match Types","t":"Match Types","d":"","k":"static"},
{"l":"new-types/dependent-function-types.html#","e":false,"n":"Dependent Function Types","t":"Dependent Function Types","d":"","k":"static"},
{"l":"new-types/dependent-function-types-spec.html#","e":false,"n":"Dependent Function Types - More Details","t":"Dependent Function Types - More Details","d":"","k":"static"},
{"l":"new-types/polymorphic-function-types.html#","e":false,"n":"Polymorphic Function Types","t":"Polymorphic Function Types","d":"","k":"static"},
{"l":"enums/index.html#","e":false,"n":"Enums","t":"Enums","d":"","k":"static"},
{"l":"enums/enums.html#","e":false,"n":"Enumerations","t":"Enumerations","d":"","k":"static"},
{"l":"enums/adts.html#","e":false,"n":"Algebraic Data Types","t":"Algebraic Data Types","d":"","k":"static"},
{"l":"enums/desugarEnums.html#","e":false,"n":"Translation of Enums and ADTs","t":"Translation of Enums and ADTs","d":"","k":"static"},
{"l":"contextual/index.html#","e":false,"n":"Contextual Abstractions","t":"Contextual Abstractions","d":"","k":"static"},
{"l":"contextual/givens.html#","e":false,"n":"Given Instances","t":"Given Instances","d":"","k":"static"},
{"l":"contextual/using-clauses.html#","e":false,"n":"Using Clauses","t":"Using Clauses","d":"","k":"static"},
{"l":"contextual/context-bounds.html#","e":false,"n":"Context Bounds","t":"Context Bounds","d":"","k":"static"},
{"l":"contextual/given-imports.html#","e":false,"n":"Importing Givens","t":"Importing Givens","d":"","k":"static"},
{"l":"contextual/extension-methods.html#","e":false,"n":"Extension Methods","t":"Extension Methods","d":"","k":"static"},
{"l":"contextual/right-associative-extension-methods.html#","e":false,"n":"Right-Associative Extension Methods: Details","t":"Right-Associative Extension Methods: Details","d":"","k":"static"},
{"l":"contextual/type-classes.html#","e":false,"n":"Implementing Type classes","t":"Implementing Type classes","d":"","k":"static"},
{"l":"contextual/derivation.html#","e":false,"n":"Type Class Derivation","t":"Type Class Derivation","d":"","k":"static"},
{"l":"contextual/derivation-macro.html#","e":false,"n":"How to write a type class `derived` method using macros","t":"How to write a type class `derived` method using macros","d":"","k":"static"},
{"l":"contextual/multiversal-equality.html#","e":false,"n":"Multiversal Equality","t":"Multiversal Equality","d":"","k":"static"},
{"l":"contextual/context-functions.html#","e":false,"n":"Context Functions","t":"Context Functions","d":"","k":"static"},
{"l":"contextual/context-functions-spec.html#","e":false,"n":"Context Functions - More Details","t":"Context Functions - More Details","d":"","k":"static"},
{"l":"contextual/conversions.html#","e":false,"n":"Implicit Conversions","t":"Implicit Conversions","d":"","k":"static"},
{"l":"contextual/by-name-context-parameters.html#","e":false,"n":"By-Name Context Parameters","t":"By-Name Context Parameters","d":"","k":"static"},
{"l":"contextual/relationship-implicits.html#","e":false,"n":"Relationship with Scala 2 Implicits","t":"Relationship with Scala 2 Implicits","d":"","k":"static"},
{"l":"metaprogramming/index.html#","e":false,"n":"Metaprogramming","t":"Metaprogramming","d":"","k":"static"},
{"l":"metaprogramming/inline.html#","e":false,"n":"Inline","t":"Inline","d":"","k":"static"},
{"l":"metaprogramming/compiletime-ops.html#","e":false,"n":"Compile-time operations","t":"Compile-time operations","d":"","k":"static"},
{"l":"metaprogramming/macros.html#","e":false,"n":"Macros","t":"Macros","d":"","k":"static"},
{"l":"metaprogramming/macros-spec.html#","e":false,"n":"Macros Spec","t":"Macros Spec","d":"","k":"static"},
{"l":"metaprogramming/staging.html#","e":false,"n":"Runtime Multi-Stage Programming","t":"Runtime Multi-Stage Programming","d":"","k":"static"},
{"l":"metaprogramming/reflection.html#","e":false,"n":"Reflection","t":"Reflection","d":"","k":"static"},
{"l":"metaprogramming/tasty-inspect.html#","e":false,"n":"TASTy Inspection","t":"TASTy Inspection","d":"","k":"static"},
{"l":"other-new-features/index.html#","e":false,"n":"Other New Features","t":"Other New Features","d":"","k":"static"},
{"l":"other-new-features/trait-parameters.html#","e":false,"n":"Trait Parameters","t":"Trait Parameters","d":"","k":"static"},
{"l":"other-new-features/transparent-traits.html#","e":false,"n":"Transparent Traits","t":"Transparent Traits","d":"","k":"static"},
{"l":"other-new-features/creator-applications.html#","e":false,"n":"Universal Apply Methods","t":"Universal Apply Methods","d":"","k":"static"},
{"l":"other-new-features/export.html#","e":false,"n":"Export Clauses","t":"Export Clauses","d":"","k":"static"},
{"l":"other-new-features/opaques.html#","e":false,"n":"Opaque Type Aliases","t":"Opaque Type Aliases","d":"","k":"static"},
{"l":"other-new-features/opaques-details.html#","e":false,"n":"Opaque Type Aliases: More Details","t":"Opaque Type Aliases: More Details","d":"","k":"static"},
{"l":"other-new-features/open-classes.html#","e":false,"n":"Open Classes","t":"Open Classes","d":"","k":"static"},
{"l":"other-new-features/parameter-untupling.html#","e":false,"n":"Parameter Untupling","t":"Parameter Untupling","d":"","k":"static"},
{"l":"other-new-features/parameter-untupling-spec.html#","e":false,"n":"Parameter Untupling - More Details","t":"Parameter Untupling - More Details","d":"","k":"static"},
{"l":"other-new-features/kind-polymorphism.html#","e":false,"n":"Kind Polymorphism","t":"Kind Polymorphism","d":"","k":"static"},
{"l":"other-new-features/matchable.html#","e":false,"n":"The Matchable Trait","t":"The Matchable Trait","d":"","k":"static"},
{"l":"other-new-features/threadUnsafe-annotation.html#","e":false,"n":"The @threadUnsafe annotation","t":"The @threadUnsafe annotation","d":"","k":"static"},
{"l":"other-new-features/targetName.html#","e":false,"n":"The @targetName annotation","t":"The @targetName annotation","d":"","k":"static"},
{"l":"other-new-features/control-syntax.html#","e":false,"n":"New Control Syntax","t":"New Control Syntax","d":"","k":"static"},
{"l":"other-new-features/indentation.html#","e":false,"n":"Optional Braces","t":"Optional Braces","d":"","k":"static"},
{"l":"other-new-features/safe-initialization.html#","e":false,"n":"Safe Initialization","t":"Safe Initialization","d":"","k":"static"},
{"l":"other-new-features/type-test.html#","e":false,"n":"TypeTest","t":"TypeTest","d":"","k":"static"},
{"l":"other-new-features/experimental-defs.html#","e":false,"n":"Experimental Definitions","t":"Experimental Definitions","d":"","k":"static"},
{"l":"changed-features/index.html#","e":false,"n":"Other Changed Features","t":"Other Changed Features","d":"","k":"static"},
{"l":"changed-features/numeric-literals.html#","e":false,"n":"Numeric Literals","t":"Numeric Literals","d":"","k":"static"},
{"l":"changed-features/structural-types.html#","e":false,"n":"Programmatic Structural Types","t":"Programmatic Structural Types","d":"","k":"static"},
{"l":"changed-features/structural-types-spec.html#","e":false,"n":"Programmatic Structural Types - More Details","t":"Programmatic Structural Types - More Details","d":"","k":"static"},
{"l":"changed-features/operators.html#","e":false,"n":"Rules for Operators","t":"Rules for Operators","d":"","k":"static"},
{"l":"changed-features/wildcards.html#","e":false,"n":"Wildcard Arguments in Types","t":"Wildcard Arguments in Types","d":"","k":"static"},
{"l":"changed-features/imports.html#","e":false,"n":"Imports","t":"Imports","d":"","k":"static"},
{"l":"changed-features/type-checking.html#","e":false,"n":"Changes in Type Checking","t":"Changes in Type Checking","d":"","k":"static"},
{"l":"changed-features/type-inference.html#","e":false,"n":"Changes in Type Inference","t":"Changes in Type Inference","d":"","k":"static"},
{"l":"changed-features/implicit-resolution.html#","e":false,"n":"Changes in Implicit Resolution","t":"Changes in Implicit Resolution","d":"","k":"static"},
{"l":"changed-features/implicit-conversions.html#","e":false,"n":"Implicit Conversions","t":"Implicit Conversions","d":"","k":"static"},
{"l":"changed-features/implicit-conversions-spec.html#","e":false,"n":"Implicit Conversions - More Details","t":"Implicit Conversions - More Details","d":"","k":"static"},
{"l":"changed-features/overload-resolution.html#","e":false,"n":"Changes in Overload Resolution","t":"Changes in Overload Resolution","d":"","k":"static"},
{"l":"changed-features/match-syntax.html#","e":false,"n":"Match Expressions","t":"Match Expressions","d":"","k":"static"},
{"l":"changed-features/vararg-splices.html#","e":false,"n":"Vararg Splices","t":"Vararg Splices","d":"","k":"static"},
{"l":"changed-features/pattern-bindings.html#","e":false,"n":"Pattern Bindings","t":"Pattern Bindings","d":"","k":"static"},
{"l":"changed-features/pattern-matching.html#","e":false,"n":"Option-less pattern matching","t":"Option-less pattern matching","d":"","k":"static"},
{"l":"changed-features/eta-expansion.html#","e":false,"n":"Automatic Eta Expansion","t":"Automatic Eta Expansion","d":"","k":"static"},
{"l":"changed-features/eta-expansion-spec.html#","e":false,"n":"Automatic Eta Expansion - More Details","t":"Automatic Eta Expansion - More Details","d":"","k":"static"},
{"l":"changed-features/compiler-plugins.html#","e":false,"n":"Changes in Compiler Plugins","t":"Changes in Compiler Plugins","d":"","k":"static"},
{"l":"changed-features/lazy-vals-init.html#","e":false,"n":"Lazy Vals Initialization","t":"Lazy Vals Initialization","d":"","k":"static"},
{"l":"changed-features/main-functions.html#","e":false,"n":"Main Methods","t":"Main Methods","d":"","k":"static"},
{"l":"dropped-features/index.html#","e":false,"n":"Dropped Features","t":"Dropped Features","d":"","k":"static"},
{"l":"dropped-features/delayed-init.html#","e":false,"n":"Dropped: DelayedInit","t":"Dropped: DelayedInit","d":"","k":"static"},
{"l":"dropped-features/macros.html#","e":false,"n":"Dropped: Scala 2 Macros","t":"Dropped: Scala 2 Macros","d":"","k":"static"},
{"l":"dropped-features/existential-types.html#","e":false,"n":"Dropped: Existential Types","t":"Dropped: Existential Types","d":"","k":"static"},
{"l":"dropped-features/type-projection.html#","e":false,"n":"Dropped: General Type Projection","t":"Dropped: General Type Projection","d":"","k":"static"},
{"l":"dropped-features/do-while.html#","e":false,"n":"Dropped: Do-While","t":"Dropped: Do-While","d":"","k":"static"},
{"l":"dropped-features/procedure-syntax.html#","e":false,"n":"Dropped: Procedure Syntax","t":"Dropped: Procedure Syntax","d":"","k":"static"},
{"l":"dropped-features/package-objects.html#","e":false,"n":"Dropped: Package Objects","t":"Dropped: Package Objects","d":"","k":"static"},
{"l":"dropped-features/early-initializers.html#","e":false,"n":"Dropped: Early Initializers","t":"Dropped: Early Initializers","d":"","k":"static"},
{"l":"dropped-features/class-shadowing.html#","e":false,"n":"Dropped: Class Shadowing","t":"Dropped: Class Shadowing","d":"","k":"static"},
{"l":"dropped-features/class-shadowing-spec.html#","e":false,"n":"Dropped: Class Shadowing - More Details","t":"Dropped: Class Shadowing - More Details","d":"","k":"static"},
{"l":"dropped-features/limit22.html#","e":false,"n":"Dropped: Limit 22","t":"Dropped: Limit 22","d":"","k":"static"},
{"l":"dropped-features/xml.html#","e":false,"n":"Dropped: XML Literals","t":"Dropped: XML Literals","d":"","k":"static"},
{"l":"dropped-features/symlits.html#","e":false,"n":"Dropped: Symbol Literals","t":"Dropped: Symbol Literals","d":"","k":"static"},
{"l":"dropped-features/auto-apply.html#","e":false,"n":"Dropped: Auto-Application","t":"Dropped: Auto-Application","d":"","k":"static"},
{"l":"dropped-features/weak-conformance.html#","e":false,"n":"Dropped: Weak Conformance","t":"Dropped: Weak Conformance","d":"","k":"static"},
{"l":"dropped-features/weak-conformance-spec.html#","e":false,"n":"Dropped: Weak Conformance - More Details","t":"Dropped: Weak Conformance - More Details","d":"","k":"static"},
{"l":"dropped-features/nonlocal-returns.html#","e":false,"n":"Deprecated: Nonlocal Returns","t":"Deprecated: Nonlocal Returns","d":"","k":"static"},
{"l":"dropped-features/this-qualifier.html#","e":false,"n":"Dropped: private[this] and protected[this]","t":"Dropped: private[this] and protected[this]","d":"","k":"static"},
{"l":"dropped-features/wildcard-init.html#","e":false,"n":"Dropped: Wildcard Initializer","t":"Dropped: Wildcard Initializer","d":"","k":"static"},
{"l":"experimental/index.html#","e":false,"n":"Experimental","t":"Experimental","d":"","k":"static"},
{"l":"experimental/canthrow.html#","e":false,"n":"CanThrow Capabilities","t":"CanThrow Capabilities","d":"","k":"static"},
{"l":"experimental/erased-defs.html#","e":false,"n":"Erased Definitions","t":"Erased Definitions","d":"","k":"static"},
{"l":"experimental/erased-defs-spec.html#","e":false,"n":"Erased Definitions - More Details","t":"Erased Definitions - More Details","d":"","k":"static"},
{"l":"experimental/named-typeargs.html#","e":false,"n":"Named Type Arguments","t":"Named Type Arguments","d":"","k":"static"},
{"l":"experimental/named-typeargs-spec.html#","e":false,"n":"Named Type Arguments - More Details","t":"Named Type Arguments - More Details","d":"","k":"static"},
{"l":"experimental/numeric-literals.html#","e":false,"n":"Numeric Literals","t":"Numeric Literals","d":"","k":"static"},
{"l":"experimental/explicit-nulls.html#","e":false,"n":"Explicit Nulls","t":"Explicit Nulls","d":"","k":"static"},
{"l":"experimental/main-annotation.html#","e":false,"n":"MainAnnotation","t":"MainAnnotation","d":"","k":"static"},
{"l":"experimental/cc.html#","e":false,"n":"Capture Checking","t":"Capture Checking","d":"","k":"static"},
{"l":"syntax.html#","e":false,"n":"Scala 3 Syntax Summary","t":"Scala 3 Syntax Summary","d":"","k":"static"},
{"l":"language-versions/index.html#","e":false,"n":"Language Versions","t":"Language Versions","d":"","k":"static"},
{"l":"language-versions/source-compatibility.html#","e":false,"n":"Source Compatibility","t":"Source Compatibility","d":"","k":"static"},
{"l":"language-versions/binary-compatibility.html#","e":false,"n":"Binary Compatibility","t":"Binary Compatibility","d":"","k":"static"},
{"l":"soft-modifier.html#","e":false,"n":"Soft Keywords","t":"Soft Keywords","d":"","k":"static"},
{"l":"features-classification.html#","e":false,"n":"A Classification of Proposed Language Features","t":"A Classification of Proposed Language Features","d":"","k":"static"},
{"l":"overview.html#","e":false,"n":"redirect","t":"redirect","d":"","k":"static"},
{"l":"experimental/overview.html#","e":false,"n":"redirect","t":"redirect","d":"","k":"static"},
{"l":"docs/reference/other-new-features/named-typeargs.html#","e":false,"n":"redirect","t":"redirect","d":"","k":"static"}];