pages = [{"l":"index.html#","e":false,"i":"","n":"Scala 3 Reference","t":"Scala 3 Reference","d":"","k":"static","x":""},
{"l":"new-types/index.html#","e":false,"i":"","n":"New Types","t":"New Types","d":"","k":"static","x":""},
{"l":"new-types/intersection-types.html#","e":false,"i":"","n":"Intersection Types","t":"Intersection Types","d":"","k":"static","x":""},
{"l":"new-types/intersection-types-spec.html#","e":false,"i":"","n":"Intersection Types - More Details","t":"Intersection Types - More Details","d":"","k":"static","x":""},
{"l":"new-types/union-types.html#","e":false,"i":"","n":"Union Types","t":"Union Types","d":"","k":"static","x":""},
{"l":"new-types/union-types-spec.html#","e":false,"i":"","n":"Union Types - More Details","t":"Union Types - More Details","d":"","k":"static","x":""},
{"l":"new-types/type-lambdas.html#","e":false,"i":"","n":"Type Lambdas","t":"Type Lambdas","d":"","k":"static","x":""},
{"l":"new-types/type-lambdas-spec.html#","e":false,"i":"","n":"Type Lambdas - More Details","t":"Type Lambdas - More Details","d":"","k":"static","x":""},
{"l":"new-types/match-types.html#","e":false,"i":"","n":"Match Types","t":"Match Types","d":"","k":"static","x":""},
{"l":"new-types/dependent-function-types.html#","e":false,"i":"","n":"Dependent Function Types","t":"Dependent Function Types","d":"","k":"static","x":""},
{"l":"new-types/dependent-function-types-spec.html#","e":false,"i":"","n":"Dependent Function Types - More Details","t":"Dependent Function Types - More Details","d":"","k":"static","x":""},
{"l":"new-types/polymorphic-function-types.html#","e":false,"i":"","n":"Polymorphic Function Types","t":"Polymorphic Function Types","d":"","k":"static","x":""},
{"l":"enums/index.html#","e":false,"i":"","n":"Enums","t":"Enums","d":"","k":"static","x":""},
{"l":"enums/enums.html#","e":false,"i":"","n":"Enumerations","t":"Enumerations","d":"","k":"static","x":""},
{"l":"enums/adts.html#","e":false,"i":"","n":"Algebraic Data Types","t":"Algebraic Data Types","d":"","k":"static","x":""},
{"l":"enums/desugarEnums.html#","e":false,"i":"","n":"Translation of Enums and ADTs","t":"Translation of Enums and ADTs","d":"","k":"static","x":""},
{"l":"contextual/index.html#","e":false,"i":"","n":"Contextual Abstractions","t":"Contextual Abstractions","d":"","k":"static","x":""},
{"l":"contextual/givens.html#","e":false,"i":"","n":"Given Instances","t":"Given Instances","d":"","k":"static","x":""},
{"l":"contextual/using-clauses.html#","e":false,"i":"","n":"Using Clauses","t":"Using Clauses","d":"","k":"static","x":""},
{"l":"contextual/context-bounds.html#","e":false,"i":"","n":"Context Bounds","t":"Context Bounds","d":"","k":"static","x":""},
{"l":"contextual/deferred-givens.html#","e":false,"i":"","n":"Deferred Givens","t":"Deferred Givens","d":"","k":"static","x":""},
{"l":"contextual/given-imports.html#","e":false,"i":"","n":"Importing Givens","t":"Importing Givens","d":"","k":"static","x":""},
{"l":"contextual/more-givens.html#","e":false,"i":"","n":"Other Forms Of Givens","t":"Other Forms Of Givens","d":"","k":"static","x":""},
{"l":"contextual/previous-givens.html#","e":false,"i":"","n":"Previous Given Syntax","t":"Previous Given Syntax","d":"","k":"static","x":""},
{"l":"contextual/extension-methods.html#","e":false,"i":"","n":"Extension Methods","t":"Extension Methods","d":"","k":"static","x":""},
{"l":"contextual/right-associative-extension-methods.html#","e":false,"i":"","n":"Right-Associative Extension Methods: Details","t":"Right-Associative Extension Methods: Details","d":"","k":"static","x":""},
{"l":"contextual/type-classes.html#","e":false,"i":"","n":"Implementing Type classes","t":"Implementing Type classes","d":"","k":"static","x":""},
{"l":"contextual/derivation.html#","e":false,"i":"","n":"Type Class Derivation","t":"Type Class Derivation","d":"","k":"static","x":""},
{"l":"contextual/derivation-macro.html#","e":false,"i":"","n":"How to write a type class `derived` method using macros","t":"How to write a type class `derived` method using macros","d":"","k":"static","x":""},
{"l":"contextual/multiversal-equality.html#","e":false,"i":"","n":"Multiversal Equality","t":"Multiversal Equality","d":"","k":"static","x":""},
{"l":"contextual/context-functions.html#","e":false,"i":"","n":"Context Functions","t":"Context Functions","d":"","k":"static","x":""},
{"l":"contextual/context-functions-spec.html#","e":false,"i":"","n":"Context Functions - More Details","t":"Context Functions - More Details","d":"","k":"static","x":""},
{"l":"contextual/conversions.html#","e":false,"i":"","n":"Implicit Conversions","t":"Implicit Conversions","d":"","k":"static","x":""},
{"l":"contextual/by-name-context-parameters.html#","e":false,"i":"","n":"By-Name Context Parameters","t":"By-Name Context Parameters","d":"","k":"static","x":""},
{"l":"contextual/relationship-implicits.html#","e":false,"i":"","n":"Relationship with Scala 2 Implicits","t":"Relationship with Scala 2 Implicits","d":"","k":"static","x":""},
{"l":"metaprogramming/index.html#","e":false,"i":"","n":"Metaprogramming","t":"Metaprogramming","d":"","k":"static","x":""},
{"l":"metaprogramming/inline.html#","e":false,"i":"","n":"Inline","t":"Inline","d":"","k":"static","x":""},
{"l":"metaprogramming/compiletime-ops.html#","e":false,"i":"","n":"Compile-time operations","t":"Compile-time operations","d":"","k":"static","x":""},
{"l":"metaprogramming/macros.html#","e":false,"i":"","n":"Macros","t":"Macros","d":"","k":"static","x":""},
{"l":"metaprogramming/macros-spec.html#","e":false,"i":"","n":"Macros Spec","t":"Macros Spec","d":"","k":"static","x":""},
{"l":"metaprogramming/simple-smp.html#","e":false,"i":"","n":"The Meta-theory of Symmetric Metaprogramming","t":"The Meta-theory of Symmetric Metaprogramming","d":"","k":"static","x":""},
{"l":"metaprogramming/staging.html#","e":false,"i":"","n":"Run-Time Multi-Stage Programming","t":"Run-Time Multi-Stage Programming","d":"","k":"static","x":""},
{"l":"metaprogramming/reflection.html#","e":false,"i":"","n":"Reflection","t":"Reflection","d":"","k":"static","x":""},
{"l":"metaprogramming/tasty-inspect.html#","e":false,"i":"","n":"TASTy Inspection","t":"TASTy Inspection","d":"","k":"static","x":""},
{"l":"other-new-features/index.html#","e":false,"i":"","n":"Other New Features","t":"Other New Features","d":"","k":"static","x":""},
{"l":"other-new-features/trait-parameters.html#","e":false,"i":"","n":"Trait Parameters","t":"Trait Parameters","d":"","k":"static","x":""},
{"l":"other-new-features/transparent-traits.html#","e":false,"i":"","n":"Transparent Traits and Classes","t":"Transparent Traits and Classes","d":"","k":"static","x":""},
{"l":"other-new-features/creator-applications.html#","e":false,"i":"","n":"Universal Apply Methods","t":"Universal Apply Methods","d":"","k":"static","x":""},
{"l":"other-new-features/export.html#","e":false,"i":"","n":"Export Clauses","t":"Export Clauses","d":"","k":"static","x":""},
{"l":"other-new-features/opaques.html#","e":false,"i":"","n":"Opaque Type Aliases","t":"Opaque Type Aliases","d":"","k":"static","x":""},
{"l":"other-new-features/opaques-details.html#","e":false,"i":"","n":"Opaque Type Aliases: More Details","t":"Opaque Type Aliases: More Details","d":"","k":"static","x":""},
{"l":"other-new-features/named-tuples.html#","e":false,"i":"","n":"Named Tuples","t":"Named Tuples","d":"","k":"static","x":""},
{"l":"other-new-features/open-classes.html#","e":false,"i":"","n":"Open Classes","t":"Open Classes","d":"","k":"static","x":""},
{"l":"other-new-features/parameter-untupling.html#","e":false,"i":"","n":"Parameter Untupling","t":"Parameter Untupling","d":"","k":"static","x":""},
{"l":"other-new-features/parameter-untupling-spec.html#","e":false,"i":"","n":"Parameter Untupling - More Details","t":"Parameter Untupling - More Details","d":"","k":"static","x":""},
{"l":"other-new-features/generalized-method-syntax.html#","e":false,"i":"","n":"Generalized Method Syntax","t":"Generalized Method Syntax","d":"","k":"static","x":""},
{"l":"other-new-features/kind-polymorphism.html#","e":false,"i":"","n":"Kind Polymorphism","t":"Kind Polymorphism","d":"","k":"static","x":""},
{"l":"other-new-features/matchable.html#","e":false,"i":"","n":"The Matchable Trait","t":"The Matchable Trait","d":"","k":"static","x":""},
{"l":"other-new-features/threadUnsafe-annotation.html#","e":false,"i":"","n":"The @threadUnsafe annotation","t":"The @threadUnsafe annotation","d":"","k":"static","x":""},
{"l":"other-new-features/targetName.html#","e":false,"i":"","n":"The @targetName annotation","t":"The @targetName annotation","d":"","k":"static","x":""},
{"l":"other-new-features/control-syntax.html#","e":false,"i":"","n":"New Control Syntax","t":"New Control Syntax","d":"","k":"static","x":""},
{"l":"other-new-features/indentation.html#","e":false,"i":"","n":"Optional Braces","t":"Optional Braces","d":"","k":"static","x":""},
{"l":"other-new-features/safe-initialization.html#","e":false,"i":"","n":"Safe Initialization","t":"Safe Initialization","d":"","k":"static","x":""},
{"l":"other-new-features/type-test.html#","e":false,"i":"","n":"TypeTest","t":"TypeTest","d":"","k":"static","x":""},
{"l":"other-new-features/experimental-defs.html#","e":false,"i":"","n":"Experimental Definitions","t":"Experimental Definitions","d":"","k":"static","x":""},
{"l":"other-new-features/preview-defs.html#","e":false,"i":"","n":"Preview Definitions","t":"Preview Definitions","d":"","k":"static","x":""},
{"l":"other-new-features/binary-literals.html#","e":false,"i":"","n":"Binary Integer Literals","t":"Binary Integer Literals","d":"","k":"static","x":""},
{"l":"other-new-features/toplevel-definitions.html#","e":false,"i":"","n":"Toplevel Definitions","t":"Toplevel Definitions","d":"","k":"static","x":""},
{"l":"other-new-features/better-fors.html#","e":false,"i":"","n":"Better fors","t":"Better fors","d":"","k":"static","x":""},
{"l":"other-new-features/runtimeChecked.html#","e":false,"i":"","n":"The runtimeChecked method","t":"The runtimeChecked method","d":"","k":"static","x":""},
{"l":"changed-features/index.html#","e":false,"i":"","n":"Other Changed Features","t":"Other Changed Features","d":"","k":"static","x":""},
{"l":"changed-features/numeric-literals.html#","e":false,"i":"","n":"Numeric Literals","t":"Numeric Literals","d":"","k":"static","x":""},
{"l":"changed-features/structural-types.html#","e":false,"i":"","n":"Programmatic Structural Types","t":"Programmatic Structural Types","d":"","k":"static","x":""},
{"l":"changed-features/structural-types-spec.html#","e":false,"i":"","n":"Programmatic Structural Types - More Details","t":"Programmatic Structural Types - More Details","d":"","k":"static","x":""},
{"l":"changed-features/operators.html#","e":false,"i":"","n":"Rules for Operators","t":"Rules for Operators","d":"","k":"static","x":""},
{"l":"changed-features/wildcards.html#","e":false,"i":"","n":"Wildcard Arguments in Types","t":"Wildcard Arguments in Types","d":"","k":"static","x":""},
{"l":"changed-features/imports.html#","e":false,"i":"","n":"Imports","t":"Imports","d":"","k":"static","x":""},
{"l":"changed-features/type-inference.html#","e":false,"i":"","n":"Changes in Type Inference","t":"Changes in Type Inference","d":"","k":"static","x":""},
{"l":"changed-features/implicit-resolution.html#","e":false,"i":"","n":"Changes in Implicit Resolution","t":"Changes in Implicit Resolution","d":"","k":"static","x":""},
{"l":"changed-features/implicit-conversions.html#","e":false,"i":"","n":"Implicit Conversions","t":"Implicit Conversions","d":"","k":"static","x":""},
{"l":"changed-features/implicit-conversions-spec.html#","e":false,"i":"","n":"Implicit Conversions - More Details","t":"Implicit Conversions - More Details","d":"","k":"static","x":""},
{"l":"changed-features/overload-resolution.html#","e":false,"i":"","n":"Changes in Overload Resolution","t":"Changes in Overload Resolution","d":"","k":"static","x":""},
{"l":"changed-features/match-syntax.html#","e":false,"i":"","n":"Match Expressions","t":"Match Expressions","d":"","k":"static","x":""},
{"l":"changed-features/vararg-splices.html#","e":false,"i":"","n":"Vararg Splices","t":"Vararg Splices","d":"","k":"static","x":""},
{"l":"changed-features/pattern-bindings.html#","e":false,"i":"","n":"Pattern Bindings","t":"Pattern Bindings","d":"","k":"static","x":""},
{"l":"changed-features/pattern-matching.html#","e":false,"i":"","n":"Option-less pattern matching","t":"Option-less pattern matching","d":"","k":"static","x":""},
{"l":"changed-features/eta-expansion.html#","e":false,"i":"","n":"Automatic Eta Expansion","t":"Automatic Eta Expansion","d":"","k":"static","x":""},
{"l":"changed-features/eta-expansion-spec.html#","e":false,"i":"","n":"Automatic Eta Expansion - More Details","t":"Automatic Eta Expansion - More Details","d":"","k":"static","x":""},
{"l":"changed-features/compiler-plugins.html#","e":false,"i":"","n":"Changes in Compiler Plugins","t":"Changes in Compiler Plugins","d":"","k":"static","x":""},
{"l":"changed-features/lazy-vals-init.html#","e":false,"i":"","n":"Lazy Vals Initialization","t":"Lazy Vals Initialization","d":"","k":"static","x":""},
{"l":"changed-features/main-functions.html#","e":false,"i":"","n":"Main Methods","t":"Main Methods","d":"","k":"static","x":""},
{"l":"changed-features/interpolation-escapes.html#","e":false,"i":"","n":"Escapes in interpolations","t":"Escapes in interpolations","d":"","k":"static","x":""},
{"l":"dropped-features/index.html#","e":false,"i":"","n":"Dropped Features","t":"Dropped Features","d":"","k":"static","x":""},
{"l":"dropped-features/delayed-init.html#","e":false,"i":"","n":"Dropped: DelayedInit","t":"Dropped: DelayedInit","d":"","k":"static","x":""},
{"l":"dropped-features/macros.html#","e":false,"i":"","n":"Dropped: Scala 2 Macros","t":"Dropped: Scala 2 Macros","d":"","k":"static","x":""},
{"l":"dropped-features/existential-types.html#","e":false,"i":"","n":"Dropped: Existential Types","t":"Dropped: Existential Types","d":"","k":"static","x":""},
{"l":"dropped-features/type-projection.html#","e":false,"i":"","n":"Dropped: General Type Projection","t":"Dropped: General Type Projection","d":"","k":"static","x":""},
{"l":"dropped-features/do-while.html#","e":false,"i":"","n":"Dropped: Do-While","t":"Dropped: Do-While","d":"","k":"static","x":""},
{"l":"dropped-features/procedure-syntax.html#","e":false,"i":"","n":"Dropped: Procedure Syntax","t":"Dropped: Procedure Syntax","d":"","k":"static","x":""},
{"l":"dropped-features/package-objects.html#","e":false,"i":"","n":"Dropped: Package Objects","t":"Dropped: Package Objects","d":"","k":"static","x":""},
{"l":"dropped-features/early-initializers.html#","e":false,"i":"","n":"Dropped: Early Initializers","t":"Dropped: Early Initializers","d":"","k":"static","x":""},
{"l":"dropped-features/class-shadowing.html#","e":false,"i":"","n":"Dropped: Class Shadowing","t":"Dropped: Class Shadowing","d":"","k":"static","x":""},
{"l":"dropped-features/class-shadowing-spec.html#","e":false,"i":"","n":"Dropped: Class Shadowing - More Details","t":"Dropped: Class Shadowing - More Details","d":"","k":"static","x":""},
{"l":"dropped-features/limit22.html#","e":false,"i":"","n":"Dropped: Limit 22","t":"Dropped: Limit 22","d":"","k":"static","x":""},
{"l":"dropped-features/xml.html#","e":false,"i":"","n":"Dropped: XML Literals","t":"Dropped: XML Literals","d":"","k":"static","x":""},
{"l":"dropped-features/symlits.html#","e":false,"i":"","n":"Dropped: Symbol Literals","t":"Dropped: Symbol Literals","d":"","k":"static","x":""},
{"l":"dropped-features/auto-apply.html#","e":false,"i":"","n":"Dropped: Auto-Application","t":"Dropped: Auto-Application","d":"","k":"static","x":""},
{"l":"dropped-features/weak-conformance.html#","e":false,"i":"","n":"Dropped: Weak Conformance","t":"Dropped: Weak Conformance","d":"","k":"static","x":""},
{"l":"dropped-features/weak-conformance-spec.html#","e":false,"i":"","n":"Dropped: Weak Conformance - More Details","t":"Dropped: Weak Conformance - More Details","d":"","k":"static","x":""},
{"l":"dropped-features/nonlocal-returns.html#","e":false,"i":"","n":"Deprecated: Nonlocal Returns","t":"Deprecated: Nonlocal Returns","d":"","k":"static","x":""},
{"l":"dropped-features/this-qualifier.html#","e":false,"i":"","n":"Dropped: private[this] and protected[this]","t":"Dropped: private[this] and protected[this]","d":"","k":"static","x":""},
{"l":"dropped-features/wildcard-init.html#","e":false,"i":"","n":"Dropped: Wildcard Initializer","t":"Dropped: Wildcard Initializer","d":"","k":"static","x":""},
{"l":"preview/index.html#","e":false,"i":"","n":"Preview","t":"Preview","d":"","k":"static","x":""},
{"l":"preview/into.html#","e":false,"i":"","n":"The `into` Type and Modifier","t":"The `into` Type and Modifier","d":"","k":"static","x":""},
{"l":"experimental/index.html#","e":false,"i":"","n":"Experimental","t":"Experimental","d":"","k":"static","x":""},
{"l":"experimental/better-fors.html#","e":false,"i":"","n":"Better fors","t":"Better fors","d":"","k":"static","x":""},
{"l":"experimental/fewer-braces.html#","e":false,"i":"","n":"Fewer Braces","t":"Fewer Braces","d":"","k":"static","x":""},
{"l":"experimental/generalized-method-syntax.html#","e":false,"i":"","n":"Generalized Method Syntax","t":"Generalized Method Syntax","d":"","k":"static","x":""},
{"l":"experimental/named-tuples.html#","e":false,"i":"","n":"Named Tuples","t":"Named Tuples","d":"","k":"static","x":""},
{"l":"experimental/canthrow.html#","e":false,"i":"","n":"CanThrow Capabilities","t":"CanThrow Capabilities","d":"","k":"static","x":""},
{"l":"experimental/erased-defs.html#","e":false,"i":"","n":"Erased Definitions","t":"Erased Definitions","d":"","k":"static","x":""},
{"l":"experimental/erased-defs-spec.html#","e":false,"i":"","n":"Erased Definitions - More Details","t":"Erased Definitions - More Details","d":"","k":"static","x":""},
{"l":"experimental/named-typeargs.html#","e":false,"i":"","n":"Named Type Arguments","t":"Named Type Arguments","d":"","k":"static","x":""},
{"l":"experimental/named-typeargs-spec.html#","e":false,"i":"","n":"Named Type Arguments - More Details","t":"Named Type Arguments - More Details","d":"","k":"static","x":""},
{"l":"experimental/numeric-literals.html#","e":false,"i":"","n":"Numeric Literals","t":"Numeric Literals","d":"","k":"static","x":""},
{"l":"experimental/explicit-nulls.html#","e":false,"i":"","n":"Explicit Nulls","t":"Explicit Nulls","d":"","k":"static","x":""},
{"l":"experimental/main-annotation.html#","e":false,"i":"","n":"MainAnnotation","t":"MainAnnotation","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/index.html#","e":false,"i":"","n":"Capture Checking","t":"Capture Checking","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/overview.html#","e":false,"i":"","n":"Tracked Capabilities Overview","t":"Tracked Capabilities Overview","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/basics.html#","e":false,"i":"","n":"Capture Checking Basics","t":"Capture Checking Basics","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/classes.html#","e":false,"i":"","n":"Capture Checking of Classes","t":"Capture Checking of Classes","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/polymorphism.html#","e":false,"i":"","n":"Capability Polymorphism","t":"Capability Polymorphism","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/advanced.html#","e":false,"i":"","n":"Capability Polymorphism","t":"Capability Polymorphism","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/scoped-capabilities.html#","e":false,"i":"","n":"Scoped Capabilities","t":"Scoped Capabilities","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/classifiers.html#","e":false,"i":"","n":"Capability Classifiers","t":"Capability Classifiers","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/checked-exceptions.html#","e":false,"i":"","n":"Checked Exceptions","t":"Checked Exceptions","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/mutability.html#","e":false,"i":"","n":"Stateful Capabilities","t":"Stateful Capabilities","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/separation-checking.html#","e":false,"i":"","n":"Separation Checking","t":"Separation Checking","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/safe.html#","e":false,"i":"","n":"Safe Mode","t":"Safe Mode","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/how-to-use.html#","e":false,"i":"","n":"How to Use the Capture Checker","t":"How to Use the Capture Checker","d":"","k":"static","x":""},
{"l":"experimental/capture-checking/internals.html#","e":false,"i":"","n":"Capture Checking Internals","t":"Capture Checking Internals","d":"","k":"static","x":""},
{"l":"experimental/purefuns.html#","e":false,"i":"","n":"Pure Function Syntax","t":"Pure Function Syntax","d":"","k":"static","x":""},
{"l":"experimental/tupled-function.html#","e":false,"i":"","n":"Tupled Function","t":"Tupled Function","d":"","k":"static","x":""},
{"l":"experimental/modularity.html#","e":false,"i":"","n":"Modularity Improvements","t":"Modularity Improvements","d":"","k":"static","x":""},
{"l":"experimental/typeclasses.html#","e":false,"i":"","n":"Better Support for Type Classes","t":"Better Support for Type Classes","d":"","k":"static","x":""},
{"l":"experimental/runtimeChecked.html#","e":false,"i":"","n":"The runtimeChecked method","t":"The runtimeChecked method","d":"","k":"static","x":""},
{"l":"experimental/unrolled-defs.html#","e":false,"i":"","n":"Automatic Parameter Unrolling","t":"Automatic Parameter Unrolling","d":"","k":"static","x":""},
{"l":"experimental/package-object-values.html#","e":false,"i":"","n":"Reference-able Package Objects","t":"Reference-able Package Objects","d":"","k":"static","x":""},
{"l":"experimental/quoted-patterns-with-polymorphic-functions.html#","e":false,"i":"","n":"Quoted Patterns with Polymorphic Functions","t":"Quoted Patterns with Polymorphic Functions","d":"","k":"static","x":""},
{"l":"experimental/relaxed-lambdas.html#","e":false,"i":"","n":"Relaxed Lambda Syntax","t":"Relaxed Lambda Syntax","d":"","k":"static","x":""},
{"l":"experimental/sub-cases.html#","e":false,"i":"","n":"Match Expressions with Sub Cases","t":"Match Expressions with Sub Cases","d":"","k":"static","x":""},
{"l":"syntax.html#","e":false,"i":"","n":"Scala 3 Syntax Summary","t":"Scala 3 Syntax Summary","d":"","k":"static","x":""},
{"l":"language-versions/index.html#","e":false,"i":"","n":"Language Versions","t":"Language Versions","d":"","k":"static","x":""},
{"l":"language-versions/source-compatibility.html#","e":false,"i":"","n":"Source Compatibility","t":"Source Compatibility","d":"","k":"static","x":""},
{"l":"language-versions/binary-compatibility.html#","e":false,"i":"","n":"Binary Compatibility","t":"Binary Compatibility","d":"","k":"static","x":""},
{"l":"soft-modifier.html#","e":false,"i":"","n":"Soft Keywords","t":"Soft Keywords","d":"","k":"static","x":""},
{"l":"features-classification.html#","e":false,"i":"","n":"A Classification of Proposed Language Features","t":"A Classification of Proposed Language Features","d":"","k":"static","x":""},
{"l":"error-codes/index.html#","e":false,"i":"","n":"Error codes","t":"Error codes","d":"","k":"static","x":""},
{"l":"error-codes/E001.html#","e":false,"i":"","n":"E001: Empty Catch Block","t":"E001: Empty Catch Block","d":"","k":"static","x":""},
{"l":"error-codes/E002.html#","e":false,"i":"","n":"E002: Empty Catch And Finally Block","t":"E002: Empty Catch And Finally Block","d":"","k":"static","x":""},
{"l":"error-codes/E003.html#","e":false,"i":"","n":"E003: Deprecated With Operator","t":"E003: Deprecated With Operator","d":"","k":"static","x":""},
{"l":"error-codes/E004.html#","e":false,"i":"","n":"E004: Case Class Missing Param List","t":"E004: Case Class Missing Param List","d":"","k":"static","x":""},
{"l":"error-codes/E005.html#","e":false,"i":"","n":"E005: Duplicate Bind","t":"E005: Duplicate Bind","d":"","k":"static","x":""},
{"l":"error-codes/E006.html#","e":false,"i":"","n":"E006: Missing Ident","t":"E006: Missing Ident","d":"","k":"static","x":""},
{"l":"error-codes/E007.html#","e":false,"i":"","n":"E007: Type Mismatch","t":"E007: Type Mismatch","d":"","k":"static","x":""},
{"l":"error-codes/E008.html#","e":false,"i":"","n":"E008: Not A Member","t":"E008: Not A Member","d":"","k":"static","x":""},
{"l":"error-codes/E009.html#","e":false,"i":"","n":"E009: Early Definitions Not Supported","t":"E009: Early Definitions Not Supported","d":"","k":"static","x":""},
{"l":"error-codes/E010.html#","e":false,"i":"","n":"E010: Top Level Implicit Class","t":"E010: Top Level Implicit Class","d":"","k":"static","x":""},
{"l":"error-codes/E011.html#","e":false,"i":"","n":"E011: Implicit Case Class","t":"E011: Implicit Case Class","d":"","k":"static","x":""},
{"l":"error-codes/E012.html#","e":false,"i":"","n":"E012: Implicit Class Primary Constructor Arity","t":"E012: Implicit Class Primary Constructor Arity","d":"","k":"static","x":""},
{"l":"error-codes/E013.html#","e":false,"i":"","n":"E013: Object May Not Have Self Type","t":"E013: Object May Not Have Self Type","d":"","k":"static","x":""},
{"l":"error-codes/E014.html#","e":false,"i":"","n":"E014: Tuple Too Long","t":"E014: Tuple Too Long","d":"","k":"static","x":""},
{"l":"error-codes/E015.html#","e":false,"i":"","n":"E015: Repeated Modifier","t":"E015: Repeated Modifier","d":"","k":"static","x":""},
{"l":"error-codes/E016.html#","e":false,"i":"","n":"E016: Interpolated String Error","t":"E016: Interpolated String Error","d":"","k":"static","x":""},
{"l":"error-codes/E017.html#","e":false,"i":"","n":"E017: Unbound Placeholder Parameter","t":"E017: Unbound Placeholder Parameter","d":"","k":"static","x":""},
{"l":"error-codes/E018.html#","e":false,"i":"","n":"E018: Illegal Start Simple Expr","t":"E018: Illegal Start Simple Expr","d":"","k":"static","x":""},
{"l":"error-codes/E019.html#","e":false,"i":"","n":"E019: Missing Return Type","t":"E019: Missing Return Type","d":"","k":"static","x":""},
{"l":"error-codes/E020.html#","e":false,"i":"","n":"E020: Yield Or Do Expected In For Comprehension","t":"E020: Yield Or Do Expected In For Comprehension","d":"","k":"static","x":""},
{"l":"error-codes/E021.html#","e":false,"i":"","n":"E021: Proper Definition Not Found","t":"E021: Proper Definition Not Found","d":"","k":"static","x":""},
{"l":"error-codes/E022.html#","e":false,"i":"","n":"E022: By Name Parameter Not Supported","t":"E022: By Name Parameter Not Supported","d":"","k":"static","x":""},
{"l":"error-codes/E023.html#","e":false,"i":"","n":"E023: Wrong Number Of Type Args","t":"E023: Wrong Number Of Type Args","d":"","k":"static","x":""},
{"l":"error-codes/E024.html#","e":false,"i":"","n":"E024: Illegal Variable In Pattern Alternative","t":"E024: Illegal Variable In Pattern Alternative","d":"","k":"static","x":""},
{"l":"error-codes/E025.html#","e":false,"i":"","n":"E025: Identifier Expected","t":"E025: Identifier Expected","d":"","k":"static","x":""},
{"l":"error-codes/E026.html#","e":false,"i":"","n":"E026: Auxiliary Constructor Needs Non-Implicit Parameter","t":"E026: Auxiliary Constructor Needs Non-Implicit Parameter","d":"","k":"static","x":""},
{"l":"error-codes/E027.html#","e":false,"i":"","n":"E027: Varargs Parameter Must Come Last","t":"E027: Varargs Parameter Must Come Last","d":"","k":"static","x":""},
{"l":"error-codes/E028.html#","e":false,"i":"","n":"E028: Illegal Literal","t":"E028: Illegal Literal","d":"","k":"static","x":""},
{"l":"error-codes/E029.html#","e":false,"i":"","n":"E029: Pattern Match Exhaustivity","t":"E029: Pattern Match Exhaustivity","d":"","k":"static","x":""},
{"l":"error-codes/E030.html#","e":false,"i":"","n":"E030: Match Case Unreachable","t":"E030: Match Case Unreachable","d":"","k":"static","x":""},
{"l":"error-codes/E031.html#","e":false,"i":"","n":"E031: Sequence Wildcard Pattern Position","t":"E031: Sequence Wildcard Pattern Position","d":"","k":"static","x":""},
{"l":"error-codes/E032.html#","e":false,"i":"","n":"E032: Illegal Start Of Simple Pattern","t":"E032: Illegal Start Of Simple Pattern","d":"","k":"static","x":""},
{"l":"error-codes/E033.html#","e":false,"i":"","n":"E033: Package Duplicate Symbol","t":"E033: Package Duplicate Symbol","d":"","k":"static","x":""},
{"l":"error-codes/E034.html#","e":false,"i":"","n":"E034: Existential Types No Longer Supported","t":"E034: Existential Types No Longer Supported","d":"","k":"static","x":""},
{"l":"error-codes/E035.html#","e":false,"i":"","n":"E035: Unbound Wildcard Type","t":"E035: Unbound Wildcard Type","d":"","k":"static","x":""},
{"l":"error-codes/E036.html#","e":false,"i":"","n":"E036: Dangling This In Path","t":"E036: Dangling This In Path","d":"","k":"static","x":""},
{"l":"error-codes/E037.html#","e":false,"i":"","n":"E037: Overrides Nothing","t":"E037: Overrides Nothing","d":"","k":"static","x":""},
{"l":"error-codes/E038.html#","e":false,"i":"","n":"E038: Overrides Nothing But Name Exists","t":"E038: Overrides Nothing But Name Exists","d":"","k":"static","x":""},
{"l":"error-codes/E039.html#","e":false,"i":"","n":"E039: Forward Reference Extends Over Definition","t":"E039: Forward Reference Extends Over Definition","d":"","k":"static","x":""},
{"l":"error-codes/E040.html#","e":false,"i":"","n":"E040: Expected Token But Found","t":"E040: Expected Token But Found","d":"","k":"static","x":""},
{"l":"error-codes/E041.html#","e":false,"i":"","n":"E041: Mixed Left And Right Associative Ops","t":"E041: Mixed Left And Right Associative Ops","d":"","k":"static","x":""},
{"l":"error-codes/E042.html#","e":false,"i":"","n":"E042: Cannot Instantiate Abstract Class Or Trait","t":"E042: Cannot Instantiate Abstract Class Or Trait","d":"","k":"static","x":""},
{"l":"error-codes/E043.html#","e":false,"i":"","n":"E043: Unreducible Application","t":"E043: Unreducible Application","d":"","k":"static","x":""},
{"l":"error-codes/E044.html#","e":false,"i":"","n":"E044: Overloaded Or Recursive Method Needs Result Type","t":"E044: Overloaded Or Recursive Method Needs Result Type","d":"","k":"static","x":""},
{"l":"error-codes/E045.html#","e":false,"i":"","n":"E045: Recursive Value Needs Result Type","t":"E045: Recursive Value Needs Result Type","d":"","k":"static","x":""},
{"l":"error-codes/E046.html#","e":false,"i":"","n":"E046: Cyclic Reference Involving","t":"E046: Cyclic Reference Involving","d":"","k":"static","x":""},
{"l":"error-codes/E047.html#","e":false,"i":"","n":"E047: Cyclic Reference Involving Implicit","t":"E047: Cyclic Reference Involving Implicit","d":"","k":"static","x":""},
{"l":"error-codes/E048.html#","e":false,"i":"","n":"E048: Super Qualifier Must Be Parent","t":"E048: Super Qualifier Must Be Parent","d":"","k":"static","x":""},
{"l":"error-codes/E049.html#","e":false,"i":"","n":"E049: Ambiguous Reference","t":"E049: Ambiguous Reference","d":"","k":"static","x":""},
{"l":"error-codes/E050.html#","e":false,"i":"","n":"E050: Method Does Not Take Parameters","t":"E050: Method Does Not Take Parameters","d":"","k":"static","x":""},
{"l":"error-codes/E051.html#","e":false,"i":"","n":"E051: Ambiguous Overload","t":"E051: Ambiguous Overload","d":"","k":"static","x":""},
{"l":"error-codes/E052.html#","e":false,"i":"","n":"E052: Reassignment To Val","t":"E052: Reassignment To Val","d":"","k":"static","x":""},
{"l":"error-codes/E053.html#","e":false,"i":"","n":"E053: Type Does Not Take Parameters","t":"E053: Type Does Not Take Parameters","d":"","k":"static","x":""},
{"l":"error-codes/E054.html#","e":false,"i":"","n":"E054: Parameterized Type Lacks Arguments","t":"E054: Parameterized Type Lacks Arguments","d":"","k":"static","x":""},
{"l":"error-codes/E055.html#","e":false,"i":"","n":"E055: Var Val Parameters May Not Be Call By Name","t":"E055: Var Val Parameters May Not Be Call By Name","d":"","k":"static","x":""},
{"l":"error-codes/E056.html#","e":false,"i":"","n":"E056: Missing Type Parameter For","t":"E056: Missing Type Parameter For","d":"","k":"static","x":""},
{"l":"error-codes/E057.html#","e":false,"i":"","n":"E057: Does Not Conform To Bound","t":"E057: Does Not Conform To Bound","d":"","k":"static","x":""},
{"l":"error-codes/E058.html#","e":false,"i":"","n":"E058: Does Not Conform To Self Type","t":"E058: Does Not Conform To Self Type","d":"","k":"static","x":""},
{"l":"error-codes/E059.html#","e":false,"i":"","n":"E059: Does Not Conform To Self Type Cannot Be Instantiated","t":"E059: Does Not Conform To Self Type Cannot Be Instantiated","d":"","k":"static","x":""},
{"l":"error-codes/E060.html#","e":false,"i":"","n":"E060: Abstract Member May Not Have Modifier","t":"E060: Abstract Member May Not Have Modifier","d":"","k":"static","x":""},
{"l":"error-codes/E061.html#","e":false,"i":"","n":"E061: Top Level Can't Be Implicit","t":"E061: Top Level Can't Be Implicit","d":"","k":"static","x":""},
{"l":"error-codes/E062.html#","e":false,"i":"","n":"E062: Types And Traits Cannot Be Implicit","t":"E062: Types And Traits Cannot Be Implicit","d":"","k":"static","x":""},
{"l":"error-codes/E063.html#","e":false,"i":"","n":"E063: Only Classes Can Be Abstract","t":"E063: Only Classes Can Be Abstract","d":"","k":"static","x":""},
{"l":"error-codes/E064.html#","e":false,"i":"","n":"E064: Abstract Override Only In Traits","t":"E064: Abstract Override Only In Traits","d":"","k":"static","x":""},
{"l":"error-codes/E065.html#","e":false,"i":"","n":"E065: Traits May Not Be Final","t":"E065: Traits May Not Be Final","d":"","k":"static","x":""},
{"l":"error-codes/E066.html#","e":false,"i":"","n":"E066: Native Members May Not Have Implementation","t":"E066: Native Members May Not Have Implementation","d":"","k":"static","x":""},
{"l":"error-codes/E067.html#","e":false,"i":"","n":"E067: Only Classes Can Have Declared But Undefined Members","t":"E067: Only Classes Can Have Declared But Undefined Members","d":"","k":"static","x":""},
{"l":"error-codes/E068.html#","e":false,"i":"","n":"E068: Cannot Extend AnyVal","t":"E068: Cannot Extend AnyVal","d":"","k":"static","x":""},
{"l":"error-codes/E069.html#","e":false,"i":"","n":"E069: Cannot Have Same Name As","t":"E069: Cannot Have Same Name As","d":"","k":"static","x":""},
{"l":"error-codes/E070.html#","e":false,"i":"","n":"E070: Value Classes May Not Define Inner Class","t":"E070: Value Classes May Not Define Inner Class","d":"","k":"static","x":""},
{"l":"error-codes/E071.html#","e":false,"i":"","n":"E071: Value Classes May Not Define Non Parameter Field","t":"E071: Value Classes May Not Define Non Parameter Field","d":"","k":"static","x":""},
{"l":"error-codes/E072.html#","e":false,"i":"","n":"E072: Value Classes May Not Define A Secondary Constructor","t":"E072: Value Classes May Not Define A Secondary Constructor","d":"","k":"static","x":""},
{"l":"error-codes/E073.html#","e":false,"i":"","n":"E073: Value Classes May Not Contain Initialization","t":"E073: Value Classes May Not Contain Initialization","d":"","k":"static","x":""},
{"l":"error-codes/E074.html#","e":false,"i":"","n":"E074: Value Classes May Not Be Abstract","t":"E074: Value Classes May Not Be Abstract","d":"","k":"static","x":""},
{"l":"error-codes/E075.html#","e":false,"i":"","n":"E075: Value Classes May Not Be Contained","t":"E075: Value Classes May Not Be Contained","d":"","k":"static","x":""},
{"l":"error-codes/E076.html#","e":false,"i":"","n":"E076: Value Classes May Not Wrap Another Value Class","t":"E076: Value Classes May Not Wrap Another Value Class","d":"","k":"static","x":""},
{"l":"error-codes/E077.html#","e":false,"i":"","n":"E077: Value Class Parameter May Not Be A Var","t":"E077: Value Class Parameter May Not Be A Var","d":"","k":"static","x":""},
{"l":"error-codes/E078.html#","e":false,"i":"","n":"E078: Value Class Needs Exactly One Val Parameter","t":"E078: Value Class Needs Exactly One Val Parameter","d":"","k":"static","x":""},
{"l":"error-codes/E079.html#","e":false,"i":"","n":"E079: Only Case Class Or Case Object Allowed","t":"E079: Only Case Class Or Case Object Allowed","d":"","k":"static","x":""},
{"l":"error-codes/E080.html#","e":false,"i":"","n":"E080: Expected Top Level Def","t":"E080: Expected Top Level Def","d":"","k":"static","x":""},
{"l":"error-codes/E081.html#","e":false,"i":"","n":"E081: Anonymous Function Missing Parameter Type","t":"E081: Anonymous Function Missing Parameter Type","d":"","k":"static","x":""},
{"l":"error-codes/E082.html#","e":false,"i":"","n":"E082: Super Calls Not Allowed In Inlineable","t":"E082: Super Calls Not Allowed In Inlineable","d":"","k":"static","x":""},
{"l":"error-codes/E083.html#","e":false,"i":"","n":"E083: Not A Path","t":"E083: Not A Path","d":"","k":"static","x":""},
{"l":"error-codes/E084.html#","e":false,"i":"","n":"E084: Wildcard On Type Argument Not Allowed On New","t":"E084: Wildcard On Type Argument Not Allowed On New","d":"","k":"static","x":""},
{"l":"error-codes/E085.html#","e":false,"i":"","n":"E085: Function Type Needs Non-Empty Parameter List","t":"E085: Function Type Needs Non-Empty Parameter List","d":"","k":"static","x":""},
{"l":"error-codes/E086.html#","e":false,"i":"","n":"E086: Wrong Number Of Parameters","t":"E086: Wrong Number Of Parameters","d":"","k":"static","x":""},
{"l":"error-codes/E087.html#","e":false,"i":"","n":"E087: Duplicate Private Protected Qualifier","t":"E087: Duplicate Private Protected Qualifier","d":"","k":"static","x":""},
{"l":"error-codes/E088.html#","e":false,"i":"","n":"E088: Expected Start Of Top Level Definition","t":"E088: Expected Start Of Top Level Definition","d":"","k":"static","x":""},
{"l":"error-codes/E089.html#","e":false,"i":"","n":"E089: Missing Return Type With Return Statement","t":"E089: Missing Return Type With Return Statement","d":"","k":"static","x":""},
{"l":"error-codes/E090.html#","e":false,"i":"","n":"E090: No Return From Inlineable","t":"E090: No Return From Inlineable","d":"","k":"static","x":""},
{"l":"error-codes/E091.html#","e":false,"i":"","n":"E091: Return Outside Method Definition","t":"E091: Return Outside Method Definition","d":"","k":"static","x":""},
{"l":"error-codes/E092.html#","e":false,"i":"","n":"E092: Unchecked Type Pattern","t":"E092: Unchecked Type Pattern","d":"","k":"static","x":""},
{"l":"error-codes/E093.html#","e":false,"i":"","n":"E093: Extend Final Class","t":"E093: Extend Final Class","d":"","k":"static","x":""},
{"l":"error-codes/E094.html#","e":false,"i":"","n":"E094: Enum Case Definition In Non-Enum Owner","t":"E094: Enum Case Definition In Non-Enum Owner","d":"","k":"static","x":""},
{"l":"error-codes/E095.html#","e":false,"i":"","n":"E095: Expected Type Bound Or Equals","t":"E095: Expected Type Bound Or Equals","d":"","k":"static","x":""},
{"l":"error-codes/E096.html#","e":false,"i":"","n":"E096: Class And Companion Name Clash","t":"E096: Class And Companion Name Clash","d":"","k":"static","x":""},
{"l":"error-codes/E097.html#","e":false,"i":"","n":"E097: Tailrec Not Applicable","t":"E097: Tailrec Not Applicable","d":"","k":"static","x":""},
{"l":"error-codes/E098.html#","e":false,"i":"","n":"E098: Failure To Eliminate Existential","t":"E098: Failure To Eliminate Existential","d":"","k":"static","x":""},
{"l":"error-codes/E099.html#","e":false,"i":"","n":"E099: Only Functions Can Be Followed By Underscore","t":"E099: Only Functions Can Be Followed By Underscore","d":"","k":"static","x":""},
{"l":"error-codes/E100.html#","e":false,"i":"","n":"E100: Missing Empty Argument List","t":"E100: Missing Empty Argument List","d":"","k":"static","x":""},
{"l":"error-codes/E101.html#","e":false,"i":"","n":"E101: Duplicate Named Type Parameter","t":"E101: Duplicate Named Type Parameter","d":"","k":"static","x":""},
{"l":"error-codes/E102.html#","e":false,"i":"","n":"E102: Undefined Named Type Parameter","t":"E102: Undefined Named Type Parameter","d":"","k":"static","x":""},
{"l":"error-codes/E103.html#","e":false,"i":"","n":"E103: Illegal Start of Statement","t":"E103: Illegal Start of Statement","d":"","k":"static","x":""},
{"l":"error-codes/E104.html#","e":false,"i":"","n":"E104: Trait Is Expected","t":"E104: Trait Is Expected","d":"","k":"static","x":""},
{"l":"error-codes/E105.html#","e":false,"i":"","n":"E105: Trait Redefined Final Method From AnyRef","t":"E105: Trait Redefined Final Method From AnyRef","d":"","k":"static","x":""},
{"l":"error-codes/E106.html#","e":false,"i":"","n":"E106: Package Name Already Defined","t":"E106: Package Name Already Defined","d":"","k":"static","x":""},
{"l":"error-codes/E107.html#","e":false,"i":"","n":"E107: Unapply Invalid Number of Arguments","t":"E107: Unapply Invalid Number of Arguments","d":"","k":"static","x":""},
{"l":"error-codes/E108.html#","e":false,"i":"","n":"E108: Unapply Invalid Return Type","t":"E108: Unapply Invalid Return Type","d":"","k":"static","x":""},
{"l":"error-codes/E109.html#","e":false,"i":"","n":"E109: Static Fields Only Allowed in Objects","t":"E109: Static Fields Only Allowed in Objects","d":"","k":"static","x":""},
{"l":"error-codes/E110.html#","e":false,"i":"","n":"E110: Cyclic Inheritance","t":"E110: Cyclic Inheritance","d":"","k":"static","x":""},
{"l":"error-codes/E111.html#","e":false,"i":"","n":"E111: Bad Symbolic Reference","t":"E111: Bad Symbolic Reference","d":"","k":"static","x":""},
{"l":"error-codes/E112.html#","e":false,"i":"","n":"E112: Unable to Extend Sealed Class","t":"E112: Unable to Extend Sealed Class","d":"","k":"static","x":""},
{"l":"error-codes/E113.html#","e":false,"i":"","n":"E113: Symbol Has Unparsable Version Number","t":"E113: Symbol Has Unparsable Version Number","d":"","k":"static","x":""},
{"l":"error-codes/E114.html#","e":false,"i":"","n":"E114: Symbol Changed Semantics In Version","t":"E114: Symbol Changed Semantics In Version","d":"","k":"static","x":""},
{"l":"error-codes/E115.html#","e":false,"i":"","n":"E115: Unable to Emit Switch","t":"E115: Unable to Emit Switch","d":"","k":"static","x":""},
{"l":"error-codes/E116.html#","e":false,"i":"","n":"E116: Missing Companion for Static","t":"E116: Missing Companion for Static","d":"","k":"static","x":""},
{"l":"error-codes/E117.html#","e":false,"i":"","n":"E117: Polymorphic Method Missing Type in Parent","t":"E117: Polymorphic Method Missing Type in Parent","d":"","k":"static","x":""},
{"l":"error-codes/E118.html#","e":false,"i":"","n":"E118: Params No Inline","t":"E118: Params No Inline","d":"","k":"static","x":""},
{"l":"error-codes/E119.html#","e":false,"i":"","n":"E119: Symbol Is Not a Value","t":"E119: Symbol Is Not a Value","d":"","k":"static","x":""},
{"l":"error-codes/E120.html#","e":false,"i":"","n":"E120: Double Definition","t":"E120: Double Definition","d":"","k":"static","x":""},
{"l":"error-codes/E121.html#","e":false,"i":"","n":"E121: Match Case Only Null Warning","t":"E121: Match Case Only Null Warning","d":"","k":"static","x":""},
{"l":"error-codes/E122.html#","e":false,"i":"","n":"E122: Imported Twice","t":"E122: Imported Twice","d":"","k":"static","x":""},
{"l":"error-codes/E123.html#","e":false,"i":"","n":"E123: Type Test Always Diverges","t":"E123: Type Test Always Diverges","d":"","k":"static","x":""},
{"l":"error-codes/E124.html#","e":false,"i":"","n":"E124: Term Member Needs Result Type for Implicit Search","t":"E124: Term Member Needs Result Type for Implicit Search","d":"","k":"static","x":""},
{"l":"error-codes/E125.html#","e":false,"i":"","n":"E125: Class Cannot Extend Enum","t":"E125: Class Cannot Extend Enum","d":"","k":"static","x":""},
{"l":"error-codes/E126.html#","e":false,"i":"","n":"E126: Value Class Parameter May Not Be Call-By-Name","t":"E126: Value Class Parameter May Not Be Call-By-Name","d":"","k":"static","x":""},
{"l":"error-codes/E127.html#","e":false,"i":"","n":"E127: Not An Extractor","t":"E127: Not An Extractor","d":"","k":"static","x":""},
{"l":"error-codes/E128.html#","e":false,"i":"","n":"E128: Member With Same Name As Static","t":"E128: Member With Same Name As Static","d":"","k":"static","x":""},
{"l":"error-codes/E129.html#","e":false,"i":"","n":"E129: Pure Expression In Statement Position","t":"E129: Pure Expression In Statement Position","d":"","k":"static","x":""},
{"l":"error-codes/E130.html#","e":false,"i":"","n":"E130: Trait Companion With Mutable Static","t":"E130: Trait Companion With Mutable Static","d":"","k":"static","x":""},
{"l":"error-codes/E131.html#","e":false,"i":"","n":"E131: Lazy Static Field","t":"E131: Lazy Static Field","d":"","k":"static","x":""},
{"l":"error-codes/E132.html#","e":false,"i":"","n":"E132: Static Overriding Non-Static Members","t":"E132: Static Overriding Non-Static Members","d":"","k":"static","x":""},
{"l":"error-codes/E133.html#","e":false,"i":"","n":"E133: Overload In Refinement","t":"E133: Overload In Refinement","d":"","k":"static","x":""},
{"l":"error-codes/E134.html#","e":false,"i":"","n":"E134: No Matching Overload","t":"E134: No Matching Overload","d":"","k":"static","x":""},
{"l":"error-codes/E135.html#","e":false,"i":"","n":"E135: Stable Identifier Pattern","t":"E135: Stable Identifier Pattern","d":"","k":"static","x":""},
{"l":"error-codes/E136.html#","e":false,"i":"","n":"E136: Static Fields Should Precede Non-Static","t":"E136: Static Fields Should Precede Non-Static","d":"","k":"static","x":""},
{"l":"error-codes/E137.html#","e":false,"i":"","n":"E137: Illegal Super Accessor","t":"E137: Illegal Super Accessor","d":"","k":"static","x":""},
{"l":"error-codes/E138.html#","e":false,"i":"","n":"E138: Trait Parameter Used As Parent Prefix","t":"E138: Trait Parameter Used As Parent Prefix","d":"","k":"static","x":""},
{"l":"error-codes/E139.html#","e":false,"i":"","n":"E139: Unknown Named Enclosing Class Or Object","t":"E139: Unknown Named Enclosing Class Or Object","d":"","k":"static","x":""},
{"l":"error-codes/E140.html#","e":false,"i":"","n":"E140: Illegal Cyclic Type Reference","t":"E140: Illegal Cyclic Type Reference","d":"","k":"static","x":""},
{"l":"error-codes/E141.html#","e":false,"i":"","n":"E141: Missing Type Parameter In Type App","t":"E141: Missing Type Parameter In Type App","d":"","k":"static","x":""},
{"l":"error-codes/E142.html#","e":false,"i":"","n":"E142: Skolem in Inferred","t":"E142: Skolem in Inferred","d":"","k":"static","x":""},
{"l":"error-codes/E143.html#","e":false,"i":"","n":"E143: Erased Types Can Only Be Function Types","t":"E143: Erased Types Can Only Be Function Types","d":"","k":"static","x":""},
{"l":"error-codes/E144.html#","e":false,"i":"","n":"E144: Case Class Missing Non-Implicit Parameter List","t":"E144: Case Class Missing Non-Implicit Parameter List","d":"","k":"static","x":""},
{"l":"error-codes/E145.html#","e":false,"i":"","n":"E145: Enumerations Should Not Be Empty","t":"E145: Enumerations Should Not Be Empty","d":"","k":"static","x":""},
{"l":"error-codes/E146.html#","e":false,"i":"","n":"E146: Illegal Parameter Initialization","t":"E146: Illegal Parameter Initialization","d":"","k":"static","x":""},
{"l":"error-codes/E147.html#","e":false,"i":"","n":"E147: Redundant Modifier","t":"E147: Redundant Modifier","d":"","k":"static","x":""},
{"l":"error-codes/E148.html#","e":false,"i":"","n":"E148: Typed Case Does Not Explicitly Extend Typed Enum","t":"E148: Typed Case Does Not Explicitly Extend Typed Enum","d":"","k":"static","x":""},
{"l":"error-codes/E149.html#","e":false,"i":"","n":"E149: Illegal Redefinition Of Standard Kind","t":"E149: Illegal Redefinition Of Standard Kind","d":"","k":"static","x":""},
{"l":"error-codes/E150.html#","e":false,"i":"","n":"E150: No Extension Method Allowed","t":"E150: No Extension Method Allowed","d":"","k":"static","x":""},
{"l":"error-codes/E151.html#","e":false,"i":"","n":"E151: Extension Method Cannot Have Type Parameters","t":"E151: Extension Method Cannot Have Type Parameters","d":"","k":"static","x":""},
{"l":"error-codes/E152.html#","e":false,"i":"","n":"E152: Extension Can Only Have Defs","t":"E152: Extension Can Only Have Defs","d":"","k":"static","x":""},
{"l":"error-codes/E153.html#","e":false,"i":"","n":"E153: Unexpected Pattern For SummonFrom","t":"E153: Unexpected Pattern For SummonFrom","d":"","k":"static","x":""},
{"l":"error-codes/E154.html#","e":false,"i":"","n":"E154: Anonymous Instance Cannot Be Empty","t":"E154: Anonymous Instance Cannot Be Empty","d":"","k":"static","x":""},
{"l":"error-codes/E155.html#","e":false,"i":"","n":"E155: Type Splice in Val Pattern","t":"E155: Type Splice in Val Pattern","d":"","k":"static","x":""},
{"l":"error-codes/E156.html#","e":false,"i":"","n":"E156: Modifier Not Allowed For Definition","t":"E156: Modifier Not Allowed For Definition","d":"","k":"static","x":""},
{"l":"error-codes/E157.html#","e":false,"i":"","n":"E157: Cannot Extend Java Enum","t":"E157: Cannot Extend Java Enum","d":"","k":"static","x":""},
{"l":"error-codes/E158.html#","e":false,"i":"","n":"E158: Invalid Reference In ImplicitNotFound Annotation","t":"E158: Invalid Reference In ImplicitNotFound Annotation","d":"","k":"static","x":""},
{"l":"error-codes/E159.html#","e":false,"i":"","n":"E159: Trait May Not Define Native Method","t":"E159: Trait May Not Define Native Method","d":"","k":"static","x":""},
{"l":"error-codes/E160.html#","e":false,"i":"","n":"E160: Java Enum Parent Args","t":"E160: Java Enum Parent Args","d":"","k":"static","x":""},
{"l":"error-codes/E161.html#","e":false,"i":"","n":"E161: Already Defined","t":"E161: Already Defined","d":"","k":"static","x":""},
{"l":"error-codes/E162.html#","e":false,"i":"","n":"E162: Case Class In Inlined Code","t":"E162: Case Class In Inlined Code","d":"","k":"static","x":""},
{"l":"error-codes/E163.html#","e":false,"i":"","n":"E163: Override Type Mismatch Error","t":"E163: Override Type Mismatch Error","d":"","k":"static","x":""},
{"l":"error-codes/E164.html#","e":false,"i":"","n":"E164: Override Error","t":"E164: Override Error","d":"","k":"static","x":""},
{"l":"error-codes/E165.html#","e":false,"i":"","n":"E165: Matchable Warning","t":"E165: Matchable Warning","d":"","k":"static","x":""},
{"l":"error-codes/E166.html#","e":false,"i":"","n":"E166: Cannot Extend Function","t":"E166: Cannot Extend Function","d":"","k":"static","x":""},
{"l":"error-codes/E167.html#","e":false,"i":"","n":"E167: Lossy Widening Constant Conversion","t":"E167: Lossy Widening Constant Conversion","d":"","k":"static","x":""},
{"l":"error-codes/E168.html#","e":false,"i":"","n":"E168: Implicit Search Too Large","t":"E168: Implicit Search Too Large","d":"","k":"static","x":""},
{"l":"error-codes/E169.html#","e":false,"i":"","n":"E169: TargetName On Top-Level Class","t":"E169: TargetName On Top-Level Class","d":"","k":"static","x":""},
{"l":"error-codes/E170.html#","e":false,"i":"","n":"E170: Not Class Type","t":"E170: Not Class Type","d":"","k":"static","x":""},
{"l":"error-codes/E171.html#","e":false,"i":"","n":"E171: Missing Argument","t":"E171: Missing Argument","d":"","k":"static","x":""},
{"l":"error-codes/E172.html#","e":false,"i":"","n":"E172: Missing Implicit Argument","t":"E172: Missing Implicit Argument","d":"","k":"static","x":""},
{"l":"error-codes/E173.html#","e":false,"i":"","n":"E173: Cannot Be Accessed","t":"E173: Cannot Be Accessed","d":"","k":"static","x":""},
{"l":"error-codes/E174.html#","e":false,"i":"","n":"E174: Inline Given Should Not Be Function","t":"E174: Inline Given Should Not Be Function","d":"","k":"static","x":""},
{"l":"error-codes/E175.html#","e":false,"i":"","n":"E175: Value Discarding","t":"E175: Value Discarding","d":"","k":"static","x":""},
{"l":"error-codes/E176.html#","e":false,"i":"","n":"E176: Unused Non-Unit Value","t":"E176: Unused Non-Unit Value","d":"","k":"static","x":""},
{"l":"error-codes/E177.html#","e":false,"i":"","n":"E177: Constructor Proxy Shadows","t":"E177: Constructor Proxy Shadows","d":"","k":"static","x":""},
{"l":"error-codes/E178.html#","e":false,"i":"","n":"E178: Missing Argument List","t":"E178: Missing Argument List","d":"","k":"static","x":""},
{"l":"error-codes/E179.html#","e":false,"i":"","n":"E179: Match Type Scrutinee Cannot Be Higher-Kinded","t":"E179: Match Type Scrutinee Cannot Be Higher-Kinded","d":"","k":"static","x":""},
{"l":"error-codes/E180.html#","e":false,"i":"","n":"E180: Ambiguous Extension Method","t":"E180: Ambiguous Extension Method","d":"","k":"static","x":""},
{"l":"error-codes/E181.html#","e":false,"i":"","n":"E181: Unqualified Call to AnyRef Method","t":"E181: Unqualified Call to AnyRef Method","d":"","k":"static","x":""},
{"l":"error-codes/E182.html#","e":false,"i":"","n":"E182: Not Constant","t":"E182: Not Constant","d":"","k":"static","x":""},
{"l":"error-codes/E183.html#","e":false,"i":"","n":"E183: Closure Cannot Have Internal Parameter Dependencies","t":"E183: Closure Cannot Have Internal Parameter Dependencies","d":"","k":"static","x":""},
{"l":"error-codes/E184.html#","e":false,"i":"","n":"E184: Match Type No Cases","t":"E184: Match Type No Cases","d":"","k":"static","x":""},
{"l":"error-codes/E185.html#","e":false,"i":"","n":"E185: Unimported and Imported","t":"E185: Unimported and Imported","d":"","k":"static","x":""},
{"l":"error-codes/E186.html#","e":false,"i":"","n":"E186: Implausible Pattern Warning","t":"E186: Implausible Pattern Warning","d":"","k":"static","x":""},
{"l":"error-codes/E187.html#","e":false,"i":"","n":"E187: Synchronized Call on Boxed Class","t":"E187: Synchronized Call on Boxed Class","d":"","k":"static","x":""},
{"l":"error-codes/E188.html#","e":false,"i":"","n":"E188: VarArgs Param Cannot Be Given","t":"E188: VarArgs Param Cannot Be Given","d":"","k":"static","x":""},
{"l":"error-codes/E189.html#","e":false,"i":"","n":"E189: Extractor Not Found","t":"E189: Extractor Not Found","d":"","k":"static","x":""},
{"l":"error-codes/E190.html#","e":false,"i":"","n":"E190: Pure Unit Expression","t":"E190: Pure Unit Expression","d":"","k":"static","x":""},
{"l":"error-codes/E191.html#","e":false,"i":"","n":"E191: Match Type Legacy Pattern","t":"E191: Match Type Legacy Pattern","d":"","k":"static","x":""},
{"l":"error-codes/E192.html#","e":false,"i":"","n":"E192: Unstable Inline Accessor","t":"E192: Unstable Inline Accessor","d":"","k":"static","x":""},
{"l":"error-codes/E193.html#","e":false,"i":"","n":"E193: Volatile on Val","t":"E193: Volatile on Val","d":"","k":"static","x":""},
{"l":"error-codes/E194.html#","e":false,"i":"","n":"E194: Extension Nullified by Member","t":"E194: Extension Nullified by Member","d":"","k":"static","x":""},
{"l":"error-codes/E195.html#","e":false,"i":"","n":"E195: Phantom Symbol Not Value","t":"E195: Phantom Symbol Not Value","d":"","k":"static","x":""},
{"l":"error-codes/E196.html#","e":false,"i":"","n":"E196: Context Bound Companion Not Value","t":"E196: Context Bound Companion Not Value","d":"","k":"static","x":""},
{"l":"error-codes/E197.html#","e":false,"i":"","n":"E197: Inlined Anonymous Class Warning","t":"E197: Inlined Anonymous Class Warning","d":"","k":"static","x":""},
{"l":"error-codes/E198.html#","e":false,"i":"","n":"E198: Unused Symbol","t":"E198: Unused Symbol","d":"","k":"static","x":""},
{"l":"error-codes/E199.html#","e":false,"i":"","n":"E199: Tailrec Nested Call","t":"E199: Tailrec Nested Call","d":"","k":"static","x":""},
{"l":"error-codes/E200.html#","e":false,"i":"","n":"E200: Final Local Def","t":"E200: Final Local Def","d":"","k":"static","x":""},
{"l":"error-codes/E201.html#","e":false,"i":"","n":"E201: Non-Named Argument in Java Annotation","t":"E201: Non-Named Argument in Java Annotation","d":"","k":"static","x":""},
{"l":"error-codes/E202.html#","e":false,"i":"","n":"E202: Quoted Type Missing","t":"E202: Quoted Type Missing","d":"","k":"static","x":""},
{"l":"error-codes/E203.html#","e":false,"i":"","n":"E203: Deprecated Assignment Syntax","t":"E203: Deprecated Assignment Syntax","d":"","k":"static","x":""},
{"l":"error-codes/E204.html#","e":false,"i":"","n":"E204: Deprecated Infix Named Argument Syntax","t":"E204: Deprecated Infix Named Argument Syntax","d":"","k":"static","x":""},
{"l":"error-codes/E205.html#","e":false,"i":"","n":"E205: Given Search Priority Warning","t":"E205: Given Search Priority Warning","d":"","k":"static","x":""},
{"l":"error-codes/E206.html#","e":false,"i":"","n":"E206: Enum May Not Be Value Class","t":"E206: Enum May Not Be Value Class","d":"","k":"static","x":""},
{"l":"error-codes/E207.html#","e":false,"i":"","n":"E207: Illegal Unroll Placement","t":"E207: Illegal Unroll Placement","d":"","k":"static","x":""},
{"l":"error-codes/E208.html#","e":false,"i":"","n":"E208: Extension Has Default Receiver","t":"E208: Extension Has Default Receiver","d":"","k":"static","x":""},
{"l":"error-codes/E209.html#","e":false,"i":"","n":"E209: Format Interpolation Error","t":"E209: Format Interpolation Error","d":"","k":"static","x":""},
{"l":"error-codes/E210.html#","e":false,"i":"","n":"E210: Value Class Cannot Extend Alias of AnyVal","t":"E210: Value Class Cannot Extend Alias of AnyVal","d":"","k":"static","x":""},
{"l":"error-codes/E211.html#","e":false,"i":"","n":"E211: Match Is Not Partial Function","t":"E211: Match Is Not Partial Function","d":"","k":"static","x":""},
{"l":"error-codes/E212.html#","e":false,"i":"","n":"E212: Only Fully Dependent Applied Constructor Type","t":"E212: Only Fully Dependent Applied Constructor Type","d":"","k":"static","x":""},
{"l":"error-codes/E213.html#","e":false,"i":"","n":"E213: Pointless Applied Constructor Type","t":"E213: Pointless Applied Constructor Type","d":"","k":"static","x":""},
{"l":"error-codes/E214.html#","e":false,"i":"","n":"E214: Illegal Context Bounds","t":"E214: Illegal Context Bounds","d":"","k":"static","x":""},
{"l":"error-codes/E215.html#","e":false,"i":"","n":"E215: Named Pattern Not Applicable","t":"E215: Named Pattern Not Applicable","d":"","k":"static","x":""},
{"l":"error-codes/E216.html#","e":false,"i":"","n":"E216: Unnecessary .nn","t":"E216: Unnecessary .nn","d":"","k":"static","x":""},
{"l":"error-codes/E217.html#","e":false,"i":"","n":"E217: Erased Not Pure","t":"E217: Erased Not Pure","d":"","k":"static","x":""},
{"l":"error-codes/E218.html#","e":false,"i":"","n":"E218: Illegal Erased Definition","t":"E218: Illegal Erased Definition","d":"","k":"static","x":""},
{"l":"error-codes/E219.html#","e":false,"i":"","n":"E219: Cannot Instantiate Quoted Type Variable","t":"E219: Cannot Instantiate Quoted Type Variable","d":"","k":"static","x":""},
{"l":"error-codes/E220.html#","e":false,"i":"","n":"E220: Default Shadows Given","t":"E220: Default Shadows Given","d":"","k":"static","x":""},
{"l":"error-codes/E221.html#","e":false,"i":"","n":"E221: Recurse With Default","t":"E221: Recurse With Default","d":"","k":"static","x":""},
{"l":"error-codes/E222.html#","e":false,"i":"","n":"E222: Encoded Package Name","t":"E222: Encoded Package Name","d":"","k":"static","x":""},
{"l":"error-codes/E223.html#","e":false,"i":"","n":"E223: Cannot Be Included in Capture Set","t":"E223: Cannot Be Included in Capture Set","d":"","k":"static","x":""},
{"l":"error-codes/E224.html#","e":false,"i":"","n":"E224: Override Class","t":"E224: Override Class","d":"","k":"static","x":""},
{"l":"error-codes/E225.html#","e":false,"i":"","n":"E225: Infer Union Warning","t":"E225: Infer Union Warning","d":"","k":"static","x":""},
{"l":"error-codes/E226.html#","e":false,"i":"","n":"E226: Type Parameter Shadows Type","t":"E226: Type Parameter Shadows Type","d":"","k":"static","x":""},
{"l":"error-codes/E227.html#","e":false,"i":"","n":"E227: Private Shadows Type","t":"E227: Private Shadows Type","d":"","k":"static","x":""},
{"l":"overview.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"contextual.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"metaprogramming.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"other-new-features.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"changed-features.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"dropped-features.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"preview/overview.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"experimental/into.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"experimental/overview.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"preview/better-fors.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"preview/named-tuples.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"other-new-features/named-typeargs.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""},
{"l":"preview/runtimeChecked.html#","e":false,"i":"","n":"redirect","t":"redirect","d":"","k":"static","x":""}];